import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {}, // Keys will fallback to English if missing, but we define them here for reference or direct lookup
  kn: {
    // Header & Landing
    features: "ವೈಶಿಷ್ಟ್ಯಗಳು",
    howItWorks: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    community: "ಸಮುದಾಯ",
    reportComplaint: "ದೂರು ನೋಂದಾಯಿಸಿ",
    schemes: "ಯೋಜನೆಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    login: "ಲಾಗಿನ್",
    logout: "ಲಾಗ್ ಔಟ್",
    heroTitleLight: "ಗ್ರಾಮ ಪಂಚಾಯತ್",
    heroTitleMiddle: " ಸಬಲೀಕರಣ.",
    heroTitleBlue: "ಹಳ್ಳಿಗಳ",
    heroTitleEnd: " ಪುನರುಜ್ಜೀವನ.",
    heroDesc: "ಮುರಿದ ಬೀದಿದೀಪಗಳು, ನೀರು ಸರಬರಾಜು ಕೊರತೆ ಮತ್ತು ನೈರ್ಮಲ್ಯದಂತಹ ನಾಗರಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಲು ಗ್ರಾಮೀಣ ಸಮುದಾಯಗಳಿಗೆ ಮೀಸಲಾದ ಡಿಜಿಟಲ್ ಪೋರ್ಟಲ್.",
    btnReport: "ಹಳ್ಳಿಯ ದೂರು ದಾಖಲಿಸಿ",
    activeStatus: "ಲೈವ್",
    precisionTitle: "ನಮ್ಮ ಹಳ್ಳಿಗಳಿಗೆ",
    precisionField: "ಸ್ಮಾರ್ಟ್ ಆಡಳಿತ.",
    precisionDesc: "ನಮ್ಮ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ನಿಖರವಾದ ಜಿಪಿಎಸ್ ನಿರ್ದೇಶಾಂಕಗಳು ಮತ್ತು ಫೋಟೋ ಅಪ್‌ಲೋಡ್‌ಗಳನ್ನು ಬಳಸಿಕೊಂಡು ನಾಗರಿಕ ಕುಂದುಕೊರತೆಗಳನ್ನು ಮ್ಯಾಪ್ ಮಾಡುತ್ತದೆ, ತ್ವರಿತ ಪರಿಹಾರಗಳಿಗಾಗಿ ಕೆಲಸಗಳನ್ನು ನೇರವಾಗಿ ಪಂಚಾಯತ್ ಕ್ಷೇತ್ರ ಕಾರ್ಮಿಕರಿಗೆ ರವಾನಿಸುತ್ತದೆ.",
    evidenceLabel: "ಪರಿಶೀಲಿಸಬಹುದಾದ ಸಾರ್ವಜನಿಕ ಕೆಲಸಗಳು",
    accuracyLabel: "Panchayat Response Time",
    monitoringLabel: "PANCHAYAT WORKFLOW",
    smartPortal: "Smart Gram Panchayat Portal",
    unifiedEco: "Unified Rural",
    ecosystem: "Ecosystem.",
    reportingTitle: "VILLAGE REPORTING",
    reportingDesc: "Submit localized water leaks, road damages, power cuts, or waste dump issues with live photo proof.",
    adminTitle: "PANCHAYAT ORCHESTRATION",
    adminDesc: "Panchayat admins and Sarpanch approve complaints, allocate budgets, and dispatch workers.",
    volunteerTitle: "FIELD-WORK RESOLUTION",
    volunteerDesc: "Field personnel receive tasks, resolve infrastructure issues, and upload validation reports.",

    // Sidebar & Menus
    home: "ಮುಖಪುಟ",
    systemOverview: "ವ್ಯವಸ್ಥೆಯ ಅವಲೋಕನ",
    fieldWorkers: "ಕ್ಷೇತ್ರ ಕೆಲಸಗಾರರು",
    complaintsMgmt: "ದೂರುಗಳು",
    settings: "ಸಂಯೋಜನೆಗಳು",
    sysAdmin: "ಸಿಸ್ಟಮ್ ಅಡ್ಮಿನ್",
    citizen: "ನಾಗರಿಕ",
    budget: "ಪಂಚಾಯತ್ ಬಜೆಟ್",
    meetings: "ಸಭೆಗಳು ಮತ್ತು ನಡಾವಳಿಗಳು",
    taxes: "ಆಸ್ತಿ ತೆರಿಗೆಗಳು",
    broadcasts: "ಪಂಚಾಯತ್ ಪ್ರಕಟಣೆಗಳು",

    // Admin Dashboard Elements
    "System Overview": "ವ್ಯವಸ್ಥೆಯ ಅವಲೋಕನ",
    "GramSuvidha infrastructure dashboard and complaint routing.": "ಗ್ರಾಮಸುವಿಧಾ ಮೂಲಸೌಕರ್ಯ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಮತ್ತು ದೂರು ರವಾನೆ.",
    "TOTAL REQUESTS": "ಒಟ್ಟು ವಿನಂತಿಗಳು",
    "PENDING ACTION": "ಬಾಕಿ ಕ್ರಮ",
    "SUCCESSFUL RESOLUTIONS": "ಯಶಸ್ವಿ ಪರಿಹಾರಗಳು",
    "ACTIVE VOLUNTEERS": "ಸಕ್ರಿಯ ಸ್ವಯಂಸೇವಕರು",
    "CITIZENS": "ನಾಗರಿಕರು",
    "Panchayat Financial Intelligence": "ಪಂಚಾಯತ್ ಹಣಕಾಸು ಬುದ್ಧಿವಂತಿಕೆ",
    "Revenue and expenditure audit tracking for this fiscal year.": "ಈ ಹಣಕಾಸು ವರ್ಷದ ಆದಾಯ ಮತ್ತು ವೆಚ್ಚದ ಆಡಿಟ್ ಟ್ರ್ಯಾಕಿಂಗ್.",
    "Allocated Budget": "ಹಂಚಿಕೆ ಮಾಡಿದ ಬಜೆಟ್",
    "State/Central Allocation": "ರಾಜ್ಯ/ಕೇಂದ್ರ ಹಂಚಿಕೆ",
    "Taxes Collected": "ಸಂಗ್ರಹಿಸಿದ ತೆರಿಗೆ",
    "Tax Recovery": "ತೆರಿಗೆ ಚೇತರಿಕೆ",
    "Taxes Outstanding": "ಬಾಕಿ ಇರುವ ತೆರಿಗೆ",
    "Pending Collection": "ಬಾಕಿ ಸಂಗ್ರಹಣೆ",
    "Grievance Expenses": "ಕುಂದುಕೊರತೆ ವೆಚ್ಚಗಳು",
    "Spent on Resolutions": "ಪರಿಹಾರಗಳಿಗೆ ಖರ್ಚು ಮಾಡಿದ್ದು",
    "Available Balance": "ಲಭ್ಯವಿರುವ ಬಾಕಿ",
    "Panchayat Cash Reserve": "ಪಂಚಾಯತ್ ನಗದು ಮೀಸಲು",
    "Complaint Priority Distribution": "ದೂರು ಆದ್ಯತೆಯ ವಿತರಣೆ",
    "Real-time breakdown of filed complaints categorized by priority.": "ಆದ್ಯತೆಯ ಆಧಾರದ ಮೇಲೆ ವರ್ಗೀಕರಿಸಲಾದ ದೂರುಗಳ ನೈಜ-ಸಮಯದ ಸ್ಥಿತಿ.",
    "High Priority Tasks": "ಹೆಚ್ಚಿನ ಆದ್ಯತೆಯ ಕಾರ್ಯಗಳು",
    "Medium Priority Tasks": "ಮಧ್ಯಮ ಆದ್ಯತೆಯ ಕಾರ್ಯಗಳು",
    "Low Priority Tasks": "ಕಡಿಮೆ ಆದ್ಯತೆಯ ಕಾರ್ಯಗಳು",
    "Live Status": "ಲೈವ್ ಸ್ಥಿತಿ",
    "Operational lifecycle phase.": "ಕಾರ್ಯಾಚರಣೆಯ ಹಂತ.",
    "Incidents": "ಘಟನೆಗಳು",
    "System Intel": "ಸಿಸ್ಟಮ್ ಮಾಹಿತಿ",
    "Real-time intelligence computed from your MongoDB data.": "ನಿಮ್ಮ ಮೊಂಗೋಡಿಬಿ ಡೇಟಾದಿಂದ ಲೆಕ್ಕಹಾಕಿದ ನೈಜ-ಸಮಯದ ಮಾಹಿತಿ.",
    "LIVE": "ಲೈವ್",
    "Last updated": "ಕೊನೆಯ ನವೀಕರಣ",
    "Peak Submission Hours": "ಗರಿಷ್ಠ ಸಲ್ಲಿಕೆ ಸಮಯ",
    "Volunteer Force Status": "ಸ್ವಯಂಸೇವಕ ಪಡೆಯ ಸ್ಥಿತಿ",
    "Complaint Resolution Rate": "ದೂರು ಪರಿಹಾರ ದರ",
    "High Priority Backlog": "ಹೆಚ್ಚಿನ ಆದ್ಯತೆಯ ಬಾಕಿ ಕೆಲಸ",
    "Unassigned Complaints": "ನಿಯೋಜಿಸದ ದೂರುಗಳು",
    "Top Complaint Category": "ಪ್ರಮುಖ ದೂರು ವರ್ಗ",
    "DETECTED": "ಪತ್ತೆಹಚ್ಚಲಾಗಿದೆ",
    "HIGH": "ಹೆಚ್ಚು",
    "NEEDS ATTENTION": "ಗಮನದ ಅಗತ್ಯವಿದೆ",
    "URGENT": "ತುರ್ತು",
    "CLEAR": "ಸ್ಪಷ್ಟ",
    "ANALYSIS": "ವಿಶ್ಲೇಷಣೆ",
    "MONITORING": "ಮೇಲ್ವಿಚಾರಣೆ",
    "LOW": "ಕಡಿಮೆ",
    "MODERATE": "ಮಧ್ಯಮ",
    "EXCELLENT": "ಅತ್ಯುತ್ತಮ",
    "ACTION NEEDED": "ಕ್ರಮದ ಅಗತ್ಯವಿದೆ",
    "Connection issue — showing last known data": "ಸಂಪರ್ಕದ ಸಮಸ್ಯೆ — ಕೊನೆಯದಾಗಿ ತಿಳಿದಿರುವ ಮಾಹಿತಿಯನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ",
    "Could not load system intel": "ಸಿಸ್ಟಮ್ ಮಾಹಿತಿಯನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ",
    "Make sure the backend server is running": "ಬ್ಯಾಕೆಂಡ್ ಸರ್ವರ್ ಚಾಲನೆಯಲ್ಲಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ",
    "Retry": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    "VIEW OPERATIONAL LOG": "ಕಾರ್ಯಾಚರಣೆಯ ಲಾಗ್ ವೀಕ್ಷಿಸಿ",
    "System Operational Logs": "ಸಿಸ್ಟಮ್ ಕಾರ್ಯಾಚರಣೆಯ ಲಾಗ್‌ಗಳು",
    "Real-time status updates and admin action tracking.": "ನೈಜ-ಸಮಯದ ಸ್ಥಿತಿ ನವೀಕರಣಗಳು ಮತ್ತು ನಿರ್ವಾಹಕ ಕ್ರಿಯೆಗಳ ಟ್ರ್ಯಾಕಿಂಗ್.",
    "Close Logs": "ಲಾಗ್‌ಗಳನ್ನು ಮುಚ್ಚಿ",
    "Administrative Shortcuts": "ಆಡಳಿತಾತ್ಮಕ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು",
    "Quick links to perform administrative operations across the Panchayat modules.": "ಪಂಚಾಯತ್ ಮಾಡ್ಯೂಲ್‌ಗಳಾದ್ಯಂತ ಆಡಳಿತಾತ್ಮಕ ಕಾರ್ಯಾಚರಣೆಗಳನ್ನು ನಿರ್ವಹಿಸಲು ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು.",
    "Log Council Meeting": "ಕೌನ್ಸಿಲ್ ಸಭೆ ದಾಖಲಿಸಿ",
    "Log dates, topics discussed, citizen queries, solutions, and email minutes.": "ದಿನಾಂಕಗಳು, ಚರ್ಚಿಸಿದ ವಿಷಯಗಳು, ನಾಗರಿಕರ ಪ್ರಶ್ನೆಗಳು, ಪರಿಹಾರಗಳು ಮತ್ತು ಇಮೇಲ್ ನಡಾವಳಿಗಳನ್ನು ದಾಖಲಿಸಿ.",
    "Open Logger": "ಲಾಗರ್ ತೆರೆಯಿರಿ",
    "Configure Annual Budget": "ವಾರ್ಷಿಕ ಬಜೆಟ್ ಕಾನ್ಫಿಗರ್ ಮಾಡಿ",
    "Set total budget, allocate itemized sector funds, and trigger citizen email notifications.": "ಒಟ್ಟು ಬಜೆಟ್ ಹೊಂದಿಸಿ, ವಲಯವಾರು ಹಣವನ್ನು ಹಂಚಿಕೆ ಮಾಡಿ ಮತ್ತು ನಾಗರಿಕರ ಇಮೇಲ್ ಅಧಿಸೂಚನೆಗಳನ್ನು ಪ್ರಚೋದಿಸಿ.",
    "Allocate Budget": "ಬಜೆಟ್ ಹಂಚಿಕೆ ಮಾಡಿ",
    "Manage Complaints": "ದೂರುಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    "Dispatch field workers, audit resolution status, and manage resolution ledgers.": "ಕ್ಷೇತ್ರ ಕಾರ್ಮಿಕರನ್ನು ನಿಯೋಜಿಸಿ, ಪರಿಹಾರದ ಸ್ಥಿತಿಯನ್ನು ಆಡಿಟ್ ಮಾಡಿ ಮತ್ತು ಪರಿಹಾರ ರೆಕಾರ್ಡ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
    "Review Queue": "ಕ್ಯೂ ಪರಿಶೀಲಿಸಿ",
    "Property Tax Assessments": "ಆಸ್ತಿ ತೆರಿಗೆ ಮೌಲ್ಯಮಾಪನಗಳು",
    "Calculate local property taxes, register assessments, and audit ledger balances.": "ಸ್ಥಳೀಯ ಆಸ್ತಿ ತೆರಿಗೆಗಳನ್ನು ಲೆಕ್ಕಹಾಕಿ, ಮೌಲ್ಯಮಾಪನಗಳನ್ನು ನೋಂದಾಯಿಸಿ ಮತ್ತು ಬ್ಯಾಲೆನ್ಸ್‌ಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "Assign Assessment": "ಮೌಲ್ಯಮಾಪನ ನಿಯೋಜಿಸಿ",
    "Active Grievances Queue": "ಸಕ್ರಿಯ ದೂರುಗಳ ಕ್ಯೂ",
    "Latest unresolved citizen complaints requiring worker assignment.": "ಕಾರ್ಮಿಕರ ನಿಯೋಜನೆ ಅಗತ್ಯವಿರುವ ಇತ್ತೀಚಿನ ಪರಿಹರಿಸದ ನಾಗರಿಕ ದೂರುಗಳು.",
    "Open Full Ledger": "ಪೂರ್ಣ ಲೆಡ್ಜರ್ ತೆರೆಯಿರಿ",
    "Hello": "ನಮಸ್ಕಾರ",
    "Use this board to track pending grievances, assign public works, configure annual budgets, and publish minutes.": "ಬಾಕಿ ಇರುವ ಕುಂದುಕೊರತೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು, ಸಾರ್ವಜನಿಕ ಕೆಲಸಗಳನ್ನು ನಿಯೋಜಿಸಲು, ವಾರ್ಷಿಕ ಬಜೆಟ್‌ಗಳನ್ನು ಕಾನ್ಫಿಗರ್ ಮಾಡಲು ಮತ್ತು ನಡಾವಳಿಗಳನ್ನು ಪ್ರಕಟಿಸಲು ಈ ಬೋರ್ಡ್ ಬಳಸಿ.",
    "Gram Panchayat Administrator Dashboard": "ಗ್ರಾಮ ಪಂಚಾಯತ್ ಆಡಳಿತಗಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "PENDING": "ಬಾಕಿ ಇದೆ",
    "IN PROGRESS": "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
    "RESOLVED": "ಪರಿಹರಿಸಲಾಗಿದೆ",
    "Awaiting Review": "ಪರಿಶೀಲನೆಗಾಗಿ ಕಾಯುತ್ತಿದೆ",

    // Citizen Dashboard Elements
    "Citizen Dashboard": "ನಾಗರಿಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "Welcome back": "ಮರಳಿ ಸ್ವಾಗತ",
    "Track and manage your reported issues.": "ನಿಮ್ಮ ನಾಗರಿಕ ದೂರುಗಳು ಮತ್ತು ಅರ್ಜಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಹಾಗೂ ನಿರ್ವಹಿಸಿ.",
    "New Complaint": "ಹೊಸ ದೂರು",
    "Total": "ಒಟ್ಟು",
    "Under Review": "ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ",
    "Resolved": "ಪರಿಹರಿಸಲಾಗಿದೆ",
    "Track Complaint or Scheme": "ದೂರು ಅಥವಾ ಯೋಜನೆ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    "Enter your unique tracking ID (COMP-XXXXXXXX or SCH-XXXXXXXX) to check its status and download the receipt.": "ಅದರ ಸ್ಥಿತಿಯನ್ನು ಪರಿಶೀಲಿಸಲು ಮತ್ತು ರಶೀದಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ನಿಮ್ಮ ಅನನ್ಯ ಟ್ರ್ಯಾಕಿಂಗ್ ಐಡಿಯನ್ನು ನಮೂದಿಸಿ.",
    "Track Status": "ಸ್ಥಿತಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    "View Receipt": "ರಶೀದಿ ವೀಕ್ಷಿಸಿ",
    "Participatory Budgeting": "ಭಾಗವಹಿಸುವಿಕೆಯ ಬಜೆಟ್",
    "Every tax rupee paid by citizens is funneled back directly into village development budgets. Click below to inspect our annual Panchayat allocation values.": "ನಾಗರಿಕರು ಪಾವತಿಸುವ ಪ್ರತಿಯೊಂದು ತೆರಿಗೆ ಹಣವನ್ನು ನೇರವಾಗಿ ಗ್ರಾಮ ಅಭಿವೃದ್ಧಿ ಬಜೆಟ್‌ಗಳಿಗೆ ಬಳಸಲಾಗುತ್ತದೆ. ನಮ್ಮ ವಾರ್ಷಿಕ ಪಂಚಾಯತ್ ಬಜೆಟ್ ಪರಿಶೀಲಿಸಲು ಕೆಳಗೆ ಕ್ಲಿಕ್ ಮಾಡಿ.",
    "View Panchayat Budget": "ಪಂಚಾಯತ್ ಬಜೆಟ್ ವೀಕ್ಷಿಸಿ",
    "My Submissions": "ನನ್ನ ಸಲ್ಲಿಕೆಗಳು",
    "Track the live progress of your reported issues.": "ನಿಮ್ಮ ವರದಿ ಮಾಡಲಾದ ಸಮಸ್ಯೆಗಳ ಪ್ರಗತಿಯನ್ನು ಲೈವ್ ಆಗಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    "All": "ಎಲ್ಲಾ",
    "Incident": "ಘಟನೆ",
    "Current Status": "ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ",
    "Incident Location": "ಘಟನೆಯ ಸ್ಥಳ",
    "Progress Stage": "ಪ್ರಗತಿಯ ಹಂತ",
    "Registered": "ನೋಂದಾಯಿಸಲಾಗಿದೆ",
    "Verified Entry": "ಪರಿಶೀಲಿಸಿದ ನಮೂದು",
    "Government Schemes Tailored to Your Reports": "ನಿಮ್ಮ ವರದಿಗಳಿಗೆ ಅನುಗುಣವಾಗಿ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    "Based on your village reports, you might be eligible for these development & welfare programs.": "ನಿಮ್ಮ ಹಳ್ಳಿಯ ವರದಿಗಳ ಆಧಾರದ ಮೇಲೆ, ನೀವು ಈ ಅಭಿವೃದ್ಧಿ ಮತ್ತು ಕಲ್ಯಾಣ ಕಾರ್ಯಕ್ರಮಗಳಿಗೆ ಅರ್ಹರಾಗಿರಬಹುದು.",
    "RECOMMENDED": "ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ",
    "View Expanded Details": "ಹೆಚ್ಚಿನ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    "Complaint Analytics": "ದೂರು ವಿಶ್ಲೇಷಣೆ",
    "Visual overview of your reporting activity.": "ನಿಮ್ಮ ದೂರು ವರದಿಗಳ ದೃಶ್ಯ ಅವಲೋಕನ.",
    "Issues By Category": "ವರ್ಗಗಳ ಆಧಾರದ ಮೇಲೆ ಸಮಸ್ಯೆಗಳು",
    "Resolution Status": "ಪರಿಹಾರದ ಸ್ಥಿತಿ",

    // New Broadcast & Language selection elements
    selectLangTitle: "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    selectLangDesc: "ನೀವು ಸಂವಹನ ನಡೆಸಲು ಬಯಸುವ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.",
    langSaveBtn: "ಉಳಿಸಿ ಮತ್ತು ಮುಂದುವರೆಯಿರಿ",
    broadcastTitle: "ಪಂಚಾಯತ್ ಪ್ರಕಟಣೆಗಳು",
    broadcastFormTitle: "ಹೊಸ ಪ್ರಕಟಣೆ ರಚಿಸಿ",
    broadcastListTitle: "ಸಕ್ರಿಯ ಪ್ರಕಟಣೆಗಳ ಬೋರ್ಡ್",
    btnBroadcast: "ಪ್ರಕಟಣೆ ಪ್ರಕಟಿಸಿ",
    categoryLabel: "ಪ್ರಕಟಣೆ ವರ್ಗ",
    dateLabel: "ನಿಗದಿತ ದಿನಾಂಕ",
    timingsLabel: "ಸಮಯ / ವಿವರಗಳು",
    descLabel: "ವಿವರವಾದ ಪ್ರಕಟಣೆ ಮಾಹಿತಿ",
    successBroadcast: "ಪ್ರಕಟಣೆ ಎಚ್ಚರಿಕೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಇಮೇಲ್ ಮತ್ತು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಅಧಿಸೂಚನೆ ಮೂಲಕ ಕಳುಹಿಸಲಾಗಿದೆ!",

    // Profile Elements
    "Citizen Profile": "ನಾಗರಿಕ ಪ್ರೊಫೈಲ್",
    "Admin Profile": "ಅಡ್ಮಿನ್ ಪ್ರೊಫೈಲ್",
    "View or edit your residency details, contact numbers, and check your assigned Panchayat Administrator.": "ನಿಮ್ಮ ವಾಸ್ತವ್ಯದ ವಿವರಗಳು, ಸಂಪರ್ಕ ಸಂಖ್ಯೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ ಅಥವಾ ಸಂಪಾದಿಸಿ ಮತ್ತು ನಿಮ್ಮ ನಿಯೋಜಿತ ಪಂಚಾಯತ್ ನಿರ್ವಾಹಕರನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "View or edit your administrative details and check system info.": "ನಿಮ್ಮ ಆಡಳಿತಾತ್ಮಕ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ ಅಥವಾ ಸಂಪಾದಿಸಿ ಮತ್ತು ಸಿಸ್ಟಮ್ ಮಾಹಿತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "Cancel Edit": "ರದ್ದುಗೊಳಿಸಿ",
    "Edit Profile": "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
    "Profile Credentials": "ಪ್ರೊಫೈಲ್ ವಿವರಗಳು",
    "Email Address": "ಇಮೇಲ್ ವಿಳಾಸ",
    "Contact Number": "ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
    "Age (Years)": "ವಯಸ್ಸು (ವರ್ಷಗಳು)",
    "Gender": "ಲಿಂಗ",
    "Registered Village": "ನೋಂದಾಯಿತ ಗ್ರಾಮ",
    "Application Language": "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ",
    "My Assigned Panchayat Administrator": "ನನ್ನ ನಿಯೋಜಿತ ಪಂಚಾಯತ್ ಆಡಳಿತಗಾರ",
    "Admin Name": "ಅಡ್ಮಿನ್ ಹೆಸರು",
    "Admin Phone": "ಅಡ್ಮಿನ್ ಫೋನ್",
    "Update Particulars": "ಮಾಹಿತಿ ನವೀಕರಿಸಿ",
    "Full Name": "ಪೂರ್ಣ ಹೆಸರು",
    "Phone Number": "ಫೋನ್ ಸಂಖ್ಯೆ",
    "Age": "ವಯಸ್ಸು",
    "Select gender": "ಲಿಂಗ ಆಯ್ಕೆಮಾಡಿ",
    "Registered Village (Locked)": "ನೋಂದಾಯಿತ ಗ್ರಾಮ (ಲಾಕ್ ಮಾಡಲಾಗಿದೆ)",
    "Citizens cannot change their village name. Please contact your Panchayat office for address verification changes.": "ನಾಗರಿಕರು ತಮ್ಮ ಗ್ರಾಮದ ಹೆಸರನ್ನು ಬದಲಾಯಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ. ವಿಳಾಸ ಪರಿಶೀಲನೆ ಬದಲಾವಣೆಗಳಿಗಾಗಿ ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪಂಚಾಯತ್ ಕಚೇರಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "Cancel": "ರದ್ದುಮಾಡಿ",
    "Save Changes": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    "My Scheme Applications": "ನನ್ನ ಯೋಜನೆ ಅರ್ಜಿಗಳು",
    "You haven't applied for any schemes yet.": "ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಯೋಜನೆಗಳಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿಲ್ಲ.",
    "Pucca": "ಪಕ್ಕಾ",
    "Semi-Pucca": "ಸೆಮಿ-ಪಕ್ಕಾ",
    "Kutcha": "ಕಚ್ಚಾ",
    "None": "ಯಾವುದೂ ಇಲ್ಲ",
    "Male": "ಪುರುಷ",
    "Female": "ಮಹಿಳೆ",
    "Other": "ಇತರ",
    "Report Civic Grievance": "ನಾಗರಿಕ ಕುಂದುಕೊರತೆ ವರದಿ ಮಾಡಿ",
    "Report water supply leaks, broken streetlights, or road potholes with photo uploads and automatic GPS lock.": "ಫೋಟೋ ಅಪ್‌ಲೋಡ್‌ಗಳು ಮತ್ತು ಸ್ವಯಂಚಾಲಿತ ಜಿಪಿಎಸ್ ಲಾಕ್‌ನೊಂದಿಗೆ ನೀರು ಸರಬರಾಜು ಸೋರಿಕೆಗಳು, ಮುರಿದ ಬೀದಿದೀಪಗಳು ಅಥವಾ ರಸ್ತೆ ಗುಂಡಿಗಳನ್ನು ವರದಿ ಮಾಡಿ.",
    "Government Scheme's": "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    "Explore, check eligibility, and apply for national welfare programs (PMAY, MGNREGA) with digital receipts.": "ಡಿಜಿಟಲ್ ರಶೀದಿಗಳೊಂದಿಗೆ ರಾಷ್ಟ್ರೀಯ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳನ್ನು (PMAY, MGNREGA) ಅನ್ವೇಷಿಸಿ, ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
    "Panchayat Budget": "ಪಂಚಾಯತ್ ಬಜೆಟ್",
    "Inspect annual development budgets, funds reserves, and itemized sector allocations visually.": "ವಾರ್ಷಿಕ ಅಭಿವೃದ್ಧಿ ಬಜೆಟ್‌ಗಳು, ನಿಧಿ ಮೀಸಲು ಮತ್ತು ವಲಯವಾರು ಹಂಚಿಕೆಗಳನ್ನು ದೃಶ್ಯ ರೂಪದಲ್ಲಿ ಪರಿಶೀಲಿಸಿ.",
    "Property Taxes": "ಆಸ್ತಿ ತೆರಿಗೆಗಳು",
    "Calculate annual property taxes using official government rules, pay dues online, and download receipts.": "ಅಧಿಕೃತ ಸರ್ಕಾರಿ ನಿಯಮಗಳನ್ನು ಬಳಸಿಕೊಂಡು ವಾರ್ಷಿಕ ಆಸ್ತಿ ತೆರಿಗೆಗಳನ್ನು ಲೆಕ್ಕಹಾಕಿ, ಬಾಕಿಯನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಪಾವತಿಸಿ ಮತ್ತು ರಶೀದಿಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.",
    "Citizen Portal Dashboard": "ನಾಗರಿಕ ಪೋರ್ಟಲ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "Welcome to GramSuvidha Digital Panchayat": "ಗ್ರಾಮಸುವಿಧಾ ಡಿಜಿಟಲ್ ಪಂಚಾಯತ್‌ಗೆ ಸ್ವಾಗತ",
    "Hello, ": "ನಮಸ್ಕಾರ, ",
    ". Access Panchayat services, track status of grievances, apply for welfare benefits, and check public council decisions online.": ". ಪಂಚಾಯತ್ ಸೇವೆಗಳನ್ನು ಪ್ರವೇಶಿಸಿ, ಕುಂದುಕೊರತೆಗಳ ಸ್ಥಿತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ಕಲ್ಯಾಣ ಯೋಜನೆಗಳಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಕೌನ್ಸಿಲ್ ನಿರ್ಧಾರಗಳನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿ.",
    "Panchayat Digital Notice Board": "ಪಂಚಾಯತ್ ಡಿಜಿಟಲ್ ನೋಟಿಸ್ ಬೋರ್ಡ್",
    "IMPORTANT ANNOUNCEMENT": "ಪ್ರಮುಖ ಪ್ರಕಟಣೆ",
    "June 2026": "ಜೂನ್ 2026",
    "Property Tax Assessment Deadline": "ಆಸ್ತಿ ತೆರಿಗೆ ಮೌಲ್ಯಮಾಪನ ಗಡುವು",
    "Citizens are requested to compute and settle their property tax bills for the current assessment cycle. Late filings will attract standard municipal cesses. Pay directly under the \"Property Taxes\" path in the sidebar.": "ನಾಗರಿಕರು ಪ್ರಸ್ತುತ ಮೌಲ್ಯಮಾಪನ ಚಕ್ರದ ಆಸ್ತಿ ತೆರಿಗೆ ಬಿಲ್‌ಗಳನ್ನು ಲೆಕ್ಕಹಾಕಲು ಮತ್ತು ಪಾವತಿಸಲು ವಿನಂತಿಸಲಾಗಿದೆ. ತಡವಾಗಿ ಸಲ್ಲಿಕೆ ಮಾಡುವುದರಿಂದ ಪ್ರಮಾಣಿತ ಪುರಸಭೆ ದಂಡವನ್ನು ವಿಧಿಸಲಾಗುತ್ತದೆ. ಸೈಡ್‌ಬಾರ್‌ನಲ್ಲಿರುವ 'ಆಸ್ತಿ ತೆರಿಗೆಗಳು' ವಿಭಾಗದಲ್ಲಿ ನೇರವಾಗಿ ಪಾವತಿಸಿ.",
    "HEALTH DRIVE": "ಆರೋಗ್ಯ ಶಿಬಿರ",
    "Universal Vaccination Camp": "ಸಾರ್ವತ್ರಿಕ ಲಸಿಕಾ ಶಿಬಿರ",
    "A free village health audit and child immunization camp will be organized at the local Panchayat community building next Monday at 09:00 AM.": "ಮುಂದಿನ ಸೋಮವಾರ ಬೆಳಿಗ್ಗೆ 09:00 ಕ್ಕೆ ಸ್ಥಳೀಯ ಪಂಚಾಯತ್ ಸಮುದಾಯ ಭವನದಲ್ಲಿ ಉಚಿತ ಗ್ರಾಮ ಆರೋಗ್ಯ ತಪಾಸಣೆ ಮತ್ತು ಮಕ್ಕಳ ಲಸಿಕಾ ಶಿಬಿರವನ್ನು ಆಯೋಜಿಸಲಾಗುತ್ತದೆ.",
    "Recent Council Assembly Minutes": "ಇತ್ತೀಚಿನ ಕೌನ್ಸಿಲ್ ಸಭೆಯ ನಡಾವಳಿಗಳು",
    "View All Minutes": "ಎಲ್ಲಾ ನಡಾವಳಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    "Checking minutes log...": "ನಡಾವಳಿಗಳ ಲಾಗ್ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    "No council meeting minutes recorded yet.": "ಇನ್ನೂ ಯಾವುದೇ ಕೌನ್ಸಿಲ್ ಸಭೆಯ ನಡಾವಳಿಗಳನ್ನು ದಾಖಲಿಸಲಾಗಿಲ್ಲ.",
    "Held:": "ನಡೆದ ದಿನಾಂಕ:",
    "Time:": "ಸಮಯ:",
    "Primary Topics Discussed:": "ಚರ್ಚಿಸಲಾದ ಪ್ರಮುಖ ವಿಷಯಗಳು:",
    "Target Civil Infrastructures before next cycle:": "ಮುಂದಿನ ಅವಧಿಗೆ ಮುನ್ನ ಗುರಿಯಾಗಿಸಿಕೊಂಡ ನಾಗರಿಕ ಮೂಲಸೌಕರ್ಯಗಳು:",
    "Quick Citizen Actions": "ನಾಗರಿಕರ ತ್ವರಿತ ಕ್ರಮಗಳು",
    "Instant shortcuts to direct services.": "ನೇರ ಸೇವೆಗಳಿಗೆ ತ್ವರಿತ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು.",
    "Need Assistance?": "ಸಹಾಯ ಬೇಕೇ?",
    "If you have questions regarding land records, scheme requirements, or tax values, try querying our AI chatbot helper in the bottom-right corner. It supports Hindi translations too!": "ಭೂ ದಾಖಲೆಗಳು, ಯೋಜನೆ ಅಗತ್ಯತೆಗಳು ಅಥವಾ ತೆರಿಗೆ ಮೌಲ್ಯಗಳ ಬಗ್ಗೆ ನಿಮಗೆ ಪ್ರಶ್ನೆಗಳಿದ್ದರೆ, ಕೆಳಗಿನ ಬಲ ಮೂಲೆಯಲ್ಲಿರುವ ನಮ್ಮ AI ಚಾಟ್‌ಬಾಟ್ ಸಹಾಯಕರನ್ನು ಕೇಳಲು ಪ್ರಯತ್ನಿಸಿ. ಇದು ಕನ್ನಡ ಮತ್ತು ಹಿಂದಿ ಅನುವಾದಗಳನ್ನೂ ಬೆಂಬಲಿಸುತ್ತದೆ!",
    "Administrative Command Portal": "ಆಡಳಿತಾತ್ಮಕ ಕಮಾಂಡ್ ಪೋರ್ಟಲ್",
    "Gram Panchayat Administrator Dashboard": "ಗ್ರಾಮ ಪಂಚಾಯತ್ ಆಡಳಿತಗಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    ". Use this board to track pending grievances, assign public works, configure annual budgets, and publish minutes.": ". ಬಾಕಿ ಇರುವ ಕುಂದುಕೊರತೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು, ಸಾರ್ವಜನಿಕ ಕೆಲಸಗಳನ್ನು ನಿಯೋಜಿಸಲು, ವಾರ್ಷಿಕ ಬಜೆಟ್‌ಗಳನ್ನು ಕಾನ್ಫಿಗರ್ ಮಾಡಲು ಮತ್ತು ನಡಾವಳಿಗಳನ್ನು ಪ್ರಕಟಿಸಲು ಈ ಬೋರ್ಡ್ ಬಳಸಿ.",
    "Pending Grievances": "ಬಾಕಿ ಇರುವ ಕುಂದುಕೊರತೆಗಳು",
    "Active Field Force": "ಸಕ್ರಿಯ ಕ್ಷೇತ್ರ ಪಡೆ",
    "Workers": "ಕಾರ್ಮಿಕರು",
    "Registered Citizens": "ನೋಂದಾಯಿತ ನಾಗರಿಕರು",
    "ID:": "ಐಡಿ:",
    "N/A": "ಲಭ್ಯವಿಲ್ಲ",
    "Meetings Concluded": "ಮುಕ್ತಾಯಗೊಂಡ ಸಭೆಗಳು",
    "sessions": "ಅಧಿವೇಶನಗಳು",
    "Unpaid Taxes Ledger": "ಪಾವತಿಸದ ತೆರಿಗೆ ಲೆಡ್ಜರ್",
    "Properties": "ಆಸ್ತಿಗಳು",
    "Administrative Shortcuts": "ಆಡಳಿತಾತ್ಮಕ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು",
    "Quick links to perform administrative operations across the Panchayat modules.": "ಪಂಚಾಯತ್ ಮಾಡ್ಯೂಲ್‌ಗಳಾದ್ಯಂತ ಆಡಳಿತಾತ್ಮಕ ಕಾರ್ಯಾಚರಣೆಗಳನ್ನು ನಿರ್ವಹಿಸಲು ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು.",
    "Active Grievances Queue": "ಸಕ್ರಿಯ ದೂರುಗಳ ಕ್ಯೂ",
    "Latest unresolved citizen complaints requiring worker assignment.": "ಕಾರ್ಮಿಕರ ನಿಯೋಜನೆ ಅಗತ್ಯವಿರುವ ಇತ್ತೀಚಿನ ಪರಿಹರಿಸದ ನಾಗರಿಕ ದೂರುಗಳು.",
    "Checking queue...": "ಕ್ಯೂ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    "No unresolved complaints. Good job!": "ಯಾವುದೇ ಬಗೆಹರಿಯದ ದೂರುಗಳಿಲ್ಲ. ಒಳ್ಳೆಯ ಕೆಲಸ!",
    "Open Full Ledger": "ಪೂರ್ಣ ಲೆಡ್ಜರ್ ತೆರೆಯಿರಿ",
    "Crore": "ಕೋಟಿ",
    "Lakh": "ಲಕ್ಷ",
    "Panchayat Budget Allocations": "ಪಂಚಾಯತ್ ಬಜೆಟ್ ಹಂಚಿಕೆಗಳು",
    "Access transparent breakdowns of the Gram Panchayat annual development budgets and visual sector allocations.": "ಗ್ರಾಮ ಪಂಚಾಯತ್ ವಾರ್ಷಿಕ ಅಭಿವೃದ್ಧಿ ಬಜೆಟ್ ಮತ್ತು ದೃಶ್ಯ ವಲಯ ಹಂಚಿಕೆಗಳ ಪಾರದರ್ಶಕ ವಿವರಗಳನ್ನು ಪ್ರವೇಶಿಸಿ.",
    "Fiscal Year:": "ಹಣಕಾಸು ವರ್ಷ:",
    "FY": "ಹಣಕಾಸು ವರ್ಷ",
    "Retrieving Budget Records...": "ಬಜೆಟ್ ದಾಖಲೆಗಳನ್ನು ಹಿಂಪಡೆಯಲಾಗುತ್ತಿದೆ...",
    "No budget details registered for fiscal year": "ಹಣಕಾಸು ವರ್ಷಕ್ಕೆ ಯಾವುದೇ ಬಜೆಟ್ ವಿವರಗಳು ನೋಂದಾಯಿಸಲ್ಪಟ್ಟಿಲ್ಲ",
    "Please check back later or select a different year.": "ದಯವಿಟ್ಟು ನಂತರ ಪರಿಶೀಲಿಸಿ ಅಥವಾ ಬೇರೆ ವರ್ಷವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    "Total Allocated Funds": "ಒಟ್ಟು ಹಂಚಿಕೆ ಮಾಡಿದ ಹಣ",
    "Development Objectives": "ಅಭಿವೃದ್ಧಿ ಉದ್ದೇಶಗಳು",
    "Sector Percentage Share": "ವಲಯ ಶೇಕಡಾವಾರು ಪಾಲು",
    "Allocation": "ಹಂಚಿಕೆ",
    "Funds Weight Analysis": "ನಿಧಿ ತೂಕದ ವಿಶ್ಲೇಷಣೆ",
    "Itemized Category Allocations": "ಐಟಂಗಳ ಆಧಾರದ ವರ್ಗಗಳ ಹಂಚಿಕೆಗಳು",
    "Sector Category": "ವಲಯ ವರ್ಗ",
    "Funding Target": "ಧನಸಹಾಯದ ಗುರಿ",
    "Amount Allocated": "ಹಂಚಿಕೆ ಮಾಡಿದ ಮೊತ್ತ",
    "General Panchayat development works.": "ಸಾಮಾನ್ಯ ಪಂಚಾಯತ್ ಅಭಿವೃದ್ಧಿ ಕಾರ್ಯಗಳು.",
    "Gram Sabha Meetings & Minutes": "ಗ್ರಾಮ ಸಭೆ ಸಭೆಗಳು ಮತ್ತು ನಡಾವಳಿಗಳು",
    "Keep track of general body discussions, citizen questions, board resolutions, and ongoing infrastructure timelines.": "ಸಾಮಾನ್ಯ ಸಭೆಯ ಚರ್ಚೆಗಳು, ನಾಗರಿಕರ ಪ್ರಶ್ನೆಗಳು, ಮಂಡಳಿಯ ನಿರ್ಣಯಗಳು ಮತ್ತು ನಡೆಯುತ್ತಿರುವ ಮೂಲಸೌಕರ್ಯಗಳ ಸಮಯಾವಳಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    "Retrieving meeting logs...": "ಸಭೆಯ ನಡಾವಳಿಗಳನ್ನು ಹಿಂಪಡೆಯಲಾಗುತ್ತಿದೆ...",
    "No meeting minutes registered by the Panchayat administration yet.": "ಪಂಚಾಯತ್ ಆಡಳಿತದಿಂದ ಇನ್ನೂ ಯಾವುದೇ ಸಭೆಯ ನಡಾವಳಿಗಳನ್ನು ದಾಖಲಿಸಲಾಗಿಲ್ಲ.",
    "Grievances and discussions are logged after each council assembly.": "ಪ್ರತಿ ಕೌನ್ಸಿಲ್ ಸಭೆಯ ನಂತರ ಕುಂದುಕೊರತೆಗಳು ಮತ್ತು ಚರ್ಚೆಗಳನ್ನು ದಾಖಲಿಸಲಾಗುತ್ತದೆ.",
    "1. Topics & Details Discussed": "1. ಚರ್ಚಿಸಲಾದ ವಿಷಯಗಳು ಮತ್ತು ವಿವರಗಳು",
    "2. Grievances Raised by Citizens": "2. ನಾಗರಿಕರು ಎತ್ತಿದ ಕುಂದುಕೊರತೆಗಳು",
    "3. Solutions & Board Resolutions": "3. ಪರಿಹಾರಗಳು ಮತ್ತು ಮಂಡಳಿಯ ನಿರ್ಣಯಗಳು",
    "4. Immediate Actions Needed": "4. ತಕ್ಷಣದ ಕ್ರಮಗಳು ಅಗತ್ಯವಿದೆ",
    "5. Target Developments Before Next Council Assembly": "5. ಮುಂದಿನ ಕೌನ್ಸಿಲ್ ಸಭೆಗೆ ಮುನ್ನ ಗುರಿಯಾಗಿಸಿಕೊಂಡ ಅಭಿವೃದ್ಧಿ ಕಾರ್ಯಗಳು",

    // AdminMeetings
    "Failed to fetch meeting records.": "ಸಭೆಯ ದಾಖಲೆಗಳನ್ನು ಹಿಂಪಡೆಯಲು ವಿಫಲವಾಗಿದೆ.",
    "Network error loading meetings.": "ಸಭೆಗಳನ್ನು ಲೋಡ್ ಮಾಡುವಲ್ಲಿ ನೆಟ್‌ವರ್ಕ್ ದೋಷ.",
    "Please fill in all meeting log fields.": "ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಸಭೆಯ ಲಾಗ್ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
    "Meeting minutes registered successfully! Citizens are being notified via email.": "ಸಭೆಯ ನಡಾವಳಿಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ! ನಾಗರಿಕರಿಗೆ ಇಮೇಲ್ ಮೂಲಕ ತಿಳಿಸಲಾಗುತ್ತಿದೆ.",
    "Failed to register meeting: ": "ಸಭೆಯನ್ನು ನೋಂದಾಯಿಸಲು ವಿಫಲವಾಗಿದೆ: ",
    "Error registering meeting.": "ಸಭೆಯನ್ನು ನೋಂದಾಯಿಸುವಲ್ಲಿ ದೋಷ.",
    "Meetings & Minutes Console": "ಸಭೆಗಳು ಮತ್ತು ನಡಾವಳಿಗಳ ಕನ್ಸೋಲ್",
    "Log Gram Panchayat general body minutes, citizen grievances, resolutions, and next target timelines.": "ಗ್ರಾಮ ಪಂಚಾಯತ್ ಸಾಮಾನ್ಯ ಸಭೆಯ ನಡಾವಳಿಗಳು, ನಾಗರಿಕರ ಕುಂದುಕೊರತೆಗಳು, ನಿರ್ಣಯಗಳು ಮತ್ತು ಮುಂದಿನ ಗುರಿಗಳ ಸಮಯಾವಳಿಗಳನ್ನು ದಾಖಲಿಸಿ.",
    "Log New Meeting Minutes": "ಹೊಸ ಸಭೆಯ ನಡಾವಳಿಗಳನ್ನು ದಾಖಲಿಸಿ",
    "Submitted minutes are officially logged and automatically broadcasted to all citizens.": "ಸಲ್ಲಿಸಿದ ನಡಾವಳಿಗಳನ್ನು ಅಧಿಕೃತವಾಗಿ ದಾಖಲಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಎಲ್ಲಾ ನಾಗರಿಕರಿಗೆ ಪ್ರಸಾರ ಮಾಡಲಾಗುತ್ತದೆ.",
    "Meeting Date": "ಸಭೆಯ ದಿನಾಂಕ",
    "Meeting Time": "ಸಭೆಯ ಸಮಯ",
    "1. Topics & Details Discussed": "1. ಚರ್ಚಿಸಲಾದ ವಿಷಯಗಳು ಮತ್ತು ವಿವರಗಳು",
    "2. Questions & Grievances Raised by Citizens": "2. ನಾಗರಿಕರು ಎತ್ತಿದ ಪ್ರಶ್ನೆಗಳು ಮತ್ತು ಕುಂದುಕೊರತೆಗಳು",
    "3. Solutions & Resolutions Provided": "3. ಒದಗಿಸಿದ ಪರಿಹಾರಗಳು ಮತ್ತು ನಿರ್ಣಯಗಳು",
    "4. Immediate Actions Needed": "4. ತಕ್ಷಣದ ಕ್ರಮಗಳು ಅಗತ್ಯವಿದೆ",
    "5. Infrastructure Targets Before Next Meeting": "5. ಮುಂದಿನ ಸಭೆಗೆ ಮುನ್ನ ಮೂಲಸೌಕರ್ಯದ ಗುರಿಗಳು",
    "Record summary details of key topics addressed in the general body...": "ಸಾಮಾನ್ಯ ಸಭೆಯಲ್ಲಿ ಚರ್ಚಿಸಲಾದ ಪ್ರಮುಖ ವಿಷಯಗಳ ಸಾರಾಂಶ ವಿವರಗಳನ್ನು ದಾಖಲಿಸಿ...",
    "Log specific queries, complaints, or feedback brought up by the resident body...": "ನಿವಾಸಿಗಳ ಮಂಡಳಿಯು ಎತ್ತಿದ ನಿರ್ದಿಷ್ಟ ಪ್ರಶ್ನೆಗಳು, ದೂರುಗಳು ಅಥವಾ ಪ್ರತಿಕ್ರಿಯೆಗಳನ್ನು ದಾಖಲಿಸಿ...",
    "Summarize the answers, options, or formal resolutions agreed by the board...": "ಮಂಡಳಿಯು ಒಪ್ಪಿಕೊಂಡ ಉತ್ತರಗಳು, ಆಯ್ಕೆಗಳು ಅಥವಾ ಔಪಚಾರಿಕ ನಿರ್ಣಯಗಳನ್ನು ಸಂಕ್ಷೇಪಿಸಿ...",
    "Outline immediate tasks, assigned officers, or fast-track steps...": "ತಕ್ಷಣದ ಕಾರ್ಯಗಳು, ನಿಯೋಜಿತ ಅಧಿಕಾರಿಗಳು ಅಥವಾ ತ್ವರಿತ ಹಂತಗಳ ರೂಪರೇಖೆಯನ್ನು ನೀಡಿ...",
    "Specific civil/development goals (e.g. Completing school paving, setting up solar cells)...": "ನಿರ್ದಿಷ್ಟ ನಾಗರಿಕ/ಅಭಿವೃದ್ಧಿ ಗುರಿಗಳು (ಉದಾ. ಶಾಲೆಯ ಆವರಣ ಪೂರ್ಣಗೊಳಿಸುವುದು, ಸೌರ ಫಲಕಗಳನ್ನು ಅಳವಡಿಸುವುದು)...",
    "Publishing & Broadcasting Minutes...": "ನಡಾವಳಿಗಳನ್ನು ಪ್ರಕಟಿಸಲಾಗುತ್ತಿದೆ ಮತ್ತು ಪ್ರಸಾರ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    "Save & Publish Meeting Minutes": "ಸಭೆಯ ನಡಾವಳಿಗಳನ್ನು ಉಳಿಸಿ ಮತ್ತು ಪ್ರಕಟಿಸಿ",
    "Meeting History List": "ಸಭೆಯ ಇತಿಹಾಸದ ಪಟ್ಟಿ",
    "Historical record of Panchayat minutes logged.": "ದಾಖಲಿಸಲಾದ ಪಂಚಾಯತ್ ನಡಾವಳಿಗಳ ಐತಿಹಾಸಿಕ ದಾಖಲೆ.",
    "Loading records...": "ದಾಖಲೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    "No meetings recorded yet.": "ಇನ್ನೂ ಯಾವುದೇ ಸಭೆಗಳನ್ನು ದಾಖಲಿಸಲಾಗಿಲ್ಲ.",
    "Discussion:": "ಚರ್ಚೆ:",
    "Emailed to Citizens": "ನಾಗರಿಕರಿಗೆ ಇಮೇಲ್ ಮಾಡಲಾಗಿದೆ",
    "Local copy only": "ಸ್ಥಳೀಯ ನಕಲು ಮಾತ್ರ",

    // AdminTaxes
    "Please fill out Owner Name and Citizen Email": "ದಯವಿಟ್ಟು ಮಾಲೀಕರ ಹೆಸರು ಮತ್ತು ನಾಗರಿಕರ ಇಮೇಲ್ ಅನ್ನು ಭರ್ತಿ ಮಾಡಿ",
    "Property Tax assessment registered successfully!": "ಆಸ್ತಿ ತೆರಿಗೆ ಮೌಲ್ಯಮಾಪನವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ!",
    "Failed to create assessment": "ಮೌಲ್ಯಮಾಪನವನ್ನು ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ",
    "Network error creating assessment": "ಮೌಲ್ಯಮಾಪನವನ್ನು ರಚಿಸುವಲ್ಲಿ ನೆಟ್‌ವರ್ಕ್ ದೋಷ",
    "Property Taxes Management": "ಆಸ್ತಿ ತೆರಿಗೆಗಳ ನಿರ್ವಹಣೆ",
    "Audit property details, compute Indian government rules-based taxes, and log local ledger assessments.": "ಆಸ್ತಿ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ, ಭಾರತ ಸರ್ಕಾರದ ನಿಯಮಗಳ ಆಧಾರಿತ ತೆರಿಗೆಗಳನ್ನು ಲೆಕ್ಕಹಾಕಿ ಮತ್ತು ಸ್ಥಳೀಯ ಲೆಡ್ಜರ್ ಮೌಲ್ಯಮಾಪನಗಳನ್ನು ದಾಖಲಿಸಿ.",
    "Property Tax Ledger": "ಆಸ್ತಿ ತೆರಿಗೆ ಲೆಡ್ಜರ್",
    "Search by ID or owner...": "ಐಡಿ ಅಥವಾ ಮಾಲೀಕರಿಂದ ಹುಡುಕಿ...",
    "All Statuses": "ಎಲ್ಲಾ ಸ್ಥಿತಿಗಳು",
    "Paid": "ಪಾವತಿಸಲಾಗಿದೆ",
    "Unpaid": "ಪಾವತಿಸದ",
    "Owner / Property ID": "ಮಾಲೀಕರು / ಆಸ್ತಿ ಐಡಿ",
    "Details": "ವಿವರಗಳು",
    "Annual Tax": "ವಾರ್ಷಿಕ ತೆರಿಗೆ",
    "Status": "ಸ್ಥಿತಿ",
    "Receipt / Txn ID": "ರಶೀದಿ / ಟ್ರಾನ್ಸಾಕ್ಷನ್ ಐಡಿ",
    "No records found.": "ಯಾವುದೇ ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    "Residential": "ವಸತಿ",
    "Commercial": "ವಾಣಿಜ್ಯ",
    "Industrial": "ಕೈಗಾರಿಕಾ",
    "Vacant": "ಖಾಲಿ",
    "Pucca": "ಪಕ್ಕಾ",
    "Semi-Pucca": "ಸೆಮಿ-ಪಕ್ಕಾ",
    "Kutcha": "ಕಚ್ಚಾ",
    "construction": "ನಿರ್ಮಾಣ",
    "Loading ledger...": "ಲೆಡ್ಜರ್ ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    "Assign Tax Assessment": "ತೆರಿಗೆ ಮೌಲ್ಯಮಾಪನವನ್ನು ನಿಯೋಜಿಸಿ",
    "Create property tax bills manually for village citizens.": "ಹಳ್ಳಿಯ ನಾಗರಿಕರಿಗಾಗಿ ಆಸ್ತಿ ತೆರಿಗೆ ಬಿಲ್‌ಗಳನ್ನು ಹಸ್ತಚಾಲಿತವಾಗಿ ರಚಿಸಿ.",
    "Citizen Email Address": "ನಾಗರಿಕರ ಇಮೇಲ್ ವಿಳಾಸ",
    "Owner Full Name": "ಮಾಲೀಕರ ಪೂರ್ಣ ಹೆಸರು",
    "Type": "ಪ್ರಕಾರ",
    "Construction": "ನಿರ್ಮಾಣ",
    "Area (sq ft)": "ವಿಸ್ತೀರ್ಣ (ಚದರ ಅಡಿ)",
    "Assessed Tax:": "ಮೌಲ್ಯಮಾಪನ ಮಾಡಿದ ತೆರಿಗೆ:",
    "Registering...": "ನೋಂದಾಯಿಸಲಾಗುತ್ತಿದೆ...",
    "Register Property & Bill": "ಆಸ್ತಿ ಮತ್ತು ಬಿಲ್ ನೋಂದಾಯಿಸಿ",

    // ComplaintsManagement
    "Failed to update complaint": "ದೂರನ್ನು ನವೀಕರಿಸಲು ವಿಫಲವಾಗಿದೆ",
    "Network error": "ನೆಟ್‌ವರ್ಕ್ ದೋಷ",
    "Failed to update status": "ಸ್ಥಿತಿಯನ್ನು ನವೀಕರಿಸಲು ವಿಫಲವಾಗಿದೆ",
    "Complaints": "ದೂರುಗಳು",
    "Workers Active": "ಸಕ್ರಿಯ ಕಾರ್ಮಿಕರು",
    "Detailed review and resolution of civic reports.": "ನಾಗರಿಕ ವರದಿಗಳ ವಿವರವಾದ ಪರಿಶೀಲನೆ ಮತ್ತು ಪರಿಹಾರ.",
    "Civic Complaints": "ನಾಗರಿಕ ದೂರುಗಳು",
    "Search by ID or details...": "ಐಡಿ ಅಥವಾ ವಿವರಗಳ ಮೂಲಕ ಹುಡುಕಿ...",
    "Loading complaints...": "ದೂರುಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    "Complaint Details": "ದೂರಿನ ವಿವರಗಳು",
    "Assigned Force": "ನಿಯೋಜಿತ ಸಿಬ್ಬಂದಿ",
    "Incident Location": "ಘಟನೆಯ ಸ್ಥಳ",
    "Actions": "ಕ್ರಮಗಳು",
    "No complaints found matching current search and filters.": "ಪ್ರಸ್ತುತ ಹುಡುಕಾಟ ಮತ್ತು ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಯಾವುದೇ ದೂರುಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    "View": "ವೀಕ್ಷಿಸಿ",
    "Awaiting Review": "ಪರಿಶೀಲನೆಗಾಗಿ ಕಾಯುತ್ತಿದೆ",
    "None": "ಯಾವುದೂ ಇಲ್ಲ",
    "Complaint Details — ": "ದೂರಿನ ವಿವರಗಳು — ",
    "Category": "ವರ್ಗ",
    "Citizen Details": "ನಾಗರಿಕರ ವಿವರಗಳು",
    "Name:": "ಹೆಸರು:",
    "Phone:": "ಫೋನ್:",
    "Description": "ವಿವರಣೆ",
    "Location": "ಸ್ಥಳ",
    "Visual Evidence & Attachments": "ದೃಶ್ಯ ಸಾಕ್ಷ್ಯ ಮತ್ತು ಲಗತ್ತುಗಳು",
    "View Full Image": "ಪೂರ್ಣ ಚಿತ್ರವನ್ನು ವೀಕ್ಷಿಸಿ",
    "Open": "ತೆರೆಯಿರಿ",
    "No attachments provided.": "ಯಾವುದೇ ಲಗತ್ತುಗಳನ್ನು ಒದಗಿಸಿಲ್ಲ.",
    "Update Status": "ಸ್ಥಿತಿ ನವೀಕರಿಸಿ",
    "Assign Worker": "ಕೆಲಸಗಾರನನ್ನು ನಿಯೋಜಿಸಿ",
    "Resolution Cost (₹)": "ಪರಿಹಾರ ವೆಚ್ಚ (₹)",
    "Cost Description": "ವೆಚ್ಚದ ವಿವರಣೆ",
    "Approve": "ಅನುಮೋದಿಸಿ",
    "Reject": "ತಿರಸ್ಕರಿಸಿ",
    "Close": "ಮುಚ್ಚಿ",
    "Save Changes": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",

    // FieldWorkers
    "Please fill in all fields": "ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ",
    "Worker registered successfully!": "ಕೆಲಸಗಾರನನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ!",
    "Failed to register worker": "ಕೆಲಸಗಾರನನ್ನು ನೋಂದಾಯಿಸಲು ವಿಫಲವಾಗಿದೆ",
    "Worker marked as": "ಕೆಲಸಗಾರನನ್ನು ಹೀಗೆ ಗುರುತಿಸಲಾಗಿದೆ",
    "Failed to toggle status": "ಸ್ಥಿತಿಯನ್ನು ಬದಲಾಯಿಸಲು ವಿಫಲವಾಗಿದೆ",
    "Network error updating status": "ಸ್ಥಿತಿಯನ್ನು ನವೀಕರಿಸುವಲ್ಲಿ ನೆಟ್‌ವರ್ಕ್ ದೋಷ",
    "Field Workers": "ಕ್ಷೇತ್ರ ಕೆಲಸಗಾರರು",
    "Manage and track the active GramSuvidha workforce.": "ಸಕ್ರಿಯ ಗ್ರಾಮಸುವಿಧಾ ಕಾರ್ಯಪಡೆಯನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    "Refresh List": "ಪಟ್ಟಿಯನ್ನು ನವೀಕರಿಸಿ",
    "Close Registry": "ನೋಂದಣಿಯನ್ನು ಮುಚ್ಚಿ",
    "Click Photo to Add": "ಸೇರಿಸಲು ಫೋಟೋ ಕ್ಲಿಕ್ ಮಾಡಿ",
    "Total Workers": "ಒಟ್ಟು ಕೆಲಸಗಾರರು",
    "Assigned Cases": "ನಿಯೋಜಿತ ಪ್ರಕರಣಗಳು",
    "Force Overview": "ಕಾರ್ಯಪಡೆಯ ಅವಲೋಕನ",
    "Available Workers": "ಲಭ್ಯವಿರುವ ಕೆಲಸಗಾರರು",
    "All Workers": "ಎಲ್ಲಾ ಕೆಲಸಗಾರರು",
    "Search workers...": "ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ...",
    "Loading workers...": "ಕೆಲಸಗಾರರನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    "Photo": "ಫೋಟೋ",
    "Worker Identity": "ಕೆಲಸಗಾರನ ಗುರುತು",
    "Area / Village": "ಪ್ರದೇಶ / ಗ್ರಾಮ",
    "Contact": "ಸಂಪರ್ಕ",
    "Demographics": "ಜನಸಂಖ್ಯಾ ವಿವರಗಳು",
    "Active Status Toggle": "ಸಕ್ರಿಯ ಸ್ಥಿತಿ ಟಾಗಲ್",
    "No field workers found matching search.": "ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದಿಕೆಯಾಗುವ ಯಾವುದೇ ಕ್ಷೇತ್ರ ಕೆಲಸಗಾರರು ಕಂಡುಬಂದಿಲ್ಲ.",
    "Y/O": "ವರ್ಷ",
    "Male": "ಪುರುಷ",
    "Female": "ಮಹಿಳೆ",
    "Other": "ಇತರ",
    "ACTIVE": "ಸಕ್ರಿಯ",
    "INACTIVE": "ನಿಷ್ಕ್ರಿಯ",
    "Toggle active status": "ಸಕ್ರಿಯ ಸ್ಥಿತಿಯನ್ನು ಟಾಗಲ್ ಮಾಡಿ",
    "Add New Worker": "ಹೊಸ ಕೆಲಸಗಾರನನ್ನು ಸೇರಿಸಿ",
    "Register a new field worker for the GramSuvidha force.": "ಗ್ರಾಮಸುವಿಧಾ ಕಾರ್ಯಪಡೆಗೆ ಹೊಸ ಕ್ಷೇತ್ರ ಕೆಲಸಗಾರನನ್ನು ನೋಂದಾಯಿಸಿ.",
    "Full Name": "ಪೂರ್ಣ ಹೆಸರು",
    "Phone Number": "ಫೋನ್ ಸಂಖ್ಯೆ",
    "Age": "ವಯಸ್ಸು",
    "Gender": "ಲಿಂಗ",
    "Assigned Village / Ward": "ನಿಯೋಜಿತ ಗ್ರಾಮ / ವಾರ್ಡ್",
    "Clear": "ತೆರವುಗೊಳಿಸಿ",
    "Register Worker": "ಕೆಲಸಗಾರನನ್ನು ನೋಂದಾಯಿಸಿ",

    // SchemeApplications
    "Failed to fetch applications.": "ಅರ್ಜಿಗಳನ್ನು ಹಿಂಪಡೆಯಲು ವಿಫಲವಾಗಿದೆ.",
    "Network error. Is the backend running?": "ನೆಟ್‌ವರ್ಕ್ ದೋಷ. ಬ್ಯಾಕೆಂಡ್ ಚಾಲನೆಯಲ್ಲಿದೆಯೇ?",
    "Failed to update status.": "ಸ್ಥಿತಿಯನ್ನು ನವೀಕರಿಸಲು ವಿಫಲವಾಗಿದೆ.",
    "Error connecting to backend.": "ಬ್ಯಾಕೆಂಡ್‌ಗೆ ಸಂಪರ್ಕಿಸುವಲ್ಲಿ ದೋಷ.",
    "Admin Scheme's Portal": "ಅಡ್ಮಿನ್ ಯೋಜನೆಗಳ ಪೋರ್ಟಲ್",
    "Manage scheme catalog listings and review submitted applications from citizens.": "ಯೋಜನೆಗಳ ಕ್ಯಾಟಲಾಗ್ ಪಟ್ಟಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ನಾಗರಿಕರಿಂದ ಸಲ್ಲಿಸಲಾದ ಅರ್ಜಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "Available Schemes Catalog": "ಲಭ್ಯವಿರುವ ಯೋಜನೆಗಳ ಕ್ಯಾಟಲಾಗ್",
    "Pradhan Mantri Awas Yojana (PMAY)": "ಪ್ರಧಾನ ಮಂತ್ರಿ ಆವಾಸ್ ಯೋಜನೆ (PMAY)",
    "Housing for the rural poor.": "ಗ್ರಾಮೀಣ ಬಡವರಿಗೆ ವಸತಿ.",
    "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)": "ಮಹಾತ್ಮಾ ಗಾಂಧಿ ರಾಷ್ಟ್ರೀಯ ಗ್ರಾಮೀಣ ಉದ್ಯೋಗ ಖಾತರಿ ಕಾಯ್ದೆ (MGNREGA)",
    "Guarantees 100 days of wage employment.": "100 ದಿನಗಳ ವೇತನ ಸಹಿತ ಉದ್ಯೋಗದ ಗ್ಯಾರಂಟಿ.",
    "PM Kisan Samman Nidhi (PM-KISAN)": "ಪಿಎಂ ಕಿಸಾನ್ ಸಮ್ಮಾನ್ ನಿಧಿ (PM-KISAN)",
    "Income support to all landholding farmer families.": "ಎಲ್ಲಾ ಭೂಹಿಡುವಳಿ ಹೊಂದಿರುವ ರೈತ ಕುಟುಂಬಗಳಿಗೆ ಆದಾಯ ಬೆಂಬಲ.",
    "National Social Assistance Programme (NSAP)": "ರಾಷ್ಟ್ರೀಯ ಸಾಮಾಜಿಕ ಸಹಾಯ ಕಾರ್ಯಕ್ರಮ (NSAP)",
    "Pension scheme for elderly citizens.": "ಹಿರಿಯ ನಾಗರಿಕರಿಗೆ ಪಿಂಚಣಿ ಯೋಜನೆ.",
    "Sukanya Samriddhi Yojana (SSY)": "ಸುಕನ್ಯಾ ಸಮೃದ್ಧಿ ಯೋಜನೆ (SSY)",
    "Savings scheme targeted at parents of girl children.": "ಹೆಣ್ಣು ಮಕ್ಕಳ ಪೋಷಕರನ್ನು ಗುರಿಯಾಗಿಸಿಕೊಂಡು ಉಳಿತಾಯ ಯೋಜನೆ.",
    "Jal Jeevan Mission (Har Ghar Jal)": "ಜಲ ಜೀವನ್ ಮಿಷನ್ (ಹರ್ ಘರ್ ಜಲ್)",
    "Safe and adequate drinking water through individual household tap connections.": "ವೈಯಕ್ತಿಕ ಗೃಹ ನಲ್ಲಿ ಸಂಪರ್ಕಗಳ ಮೂಲಕ ಸುರಕ್ಷಿತ ಮತ್ತು ಸಾಕಷ್ಟು ಕುಡಿಯುವ ನೀರು.",
    "Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)": "ದೀನ್ ದಯಾಳ್ ಉಪಾಧ್ಯಾಯ ಗ್ರಾಮೀಣ ಕೌಶಲ್ಯ ಯೋಜನೆ (DDU-GKY)",
    "Placement linked skill development program for rural youth.": "ಗ್ರಾಮೀಣ ಯುವಕರಿಗೆ ಉದ್ಯೋಗ ಆಧಾರಿತ ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ ಕಾರ್ಯಕ್ರಮ.",
    "Eligible Age Range:": "ಅರ್ಹ ವಯಸ್ಸಿನ ಮಿತಿ:",
    "years": "ವರ್ಷಗಳು",
    "Income Cap Limit:": "ಆದಾಯದ ಗರಿಷ್ಠ ಮಿತಿ:",
    "/ year": "/ ವರ್ಷ",
    "View Scheme Setup": "ಯೋಜನೆಯ ಸೆಟಪ್ ವೀಕ್ಷಿಸಿ",
    "Submitted Applications Registry": "ಸಲ್ಲಿಸಲಾದ ಅರ್ಜಿಗಳ ನೋಂದಣಿ",
    "Pending Action": "ಬಾಕಿ ಇರುವ ಕ್ರಮ",
    "Applicant Name": "ಅರ್ಜಿದಾರರ ಹೆಸರು",
    "Relationship": "ಸಂಬಂಧ",
    "Income Declared": "ಘೋಷಿತ ಆದಾಯ",
    "Submitted On": "ಸಲ್ಲಿಸಿದ ದಿನಾಂಕ",
    "ID Document:": "ಗುರುತಿನ ದಾಖಲೆ:",
    "Uploaded File:": "ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಫೈಲ್:",
    "View Document": "ದಾಖಲೆಯನ್ನು ವೀಕ್ಷಿಸಿ",
    "Approve App": "ಅರ್ಜಿ ಅನುಮೋದಿಸಿ",
    "Reject App": "ಅರ್ಜಿ ತಿರಸ್ಕರಿಸಿ",
    "Set Back to Pending": "ಮತ್ತೆ ಬಾಕಿ ಸ್ಥಿತಿಗೆ ಬದಲಾಯಿಸಿ",
    "Overview:": "ಅವಲೋಕನ:",
    "Benefits:": "ಪ್ರಯೋಜನಗಳು:",
    "Eligibility Criteria:": "ಅರ್ಹತೆಯ ಮಾನದಂಡಗಳು:",
    "Documents Required:": "ಅಗತ್ಯವಿರುವ ದಾಖಲೆಗಳು:",
    "Close Guidelines": "ಮಾರ್ಗಸೂಚಿಗಳನ್ನು ಮುಚ್ಚಿ",
    "Loading scheme applications...": "ಯೋಜನೆಯ ಅರ್ಜಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    "No scheme applications have been submitted yet.": "ಇನ್ನೂ ಯಾವುದೇ ಯೋಜನೆಯ ಅರ್ಜಿಗಳನ್ನು ಸಲ್ಲಿಸಲಾಗಿಲ್ಲ.",

    // CitizenBroadcasts
    "Stay updated with important announcements regarding local elections, water supply schedules, power cutoffs, and road constructions in our village.": "ನಮ್ಮ ಹಳ್ಳಿಯಲ್ಲಿ ಸ್ಥಳೀಯ ಚುನಾವಣೆಗಳು, ನೀರು ಸರಬರಾಜು ವೇಳಾಪಟ್ಟಿಗಳು, ವಿದ್ಯುತ್ ಕಡಿತ ಮತ್ತು ರಸ್ತೆ ನಿರ್ಮಾಣಗಳ ಕುರಿತು ಪ್ರಮುಖ ಪ್ರಕಟಣೆಗಳೊಂದಿಗೆ ನವೀಕೃತವಾಗಿರಿ.",
    "No announcements or alerts are currently active.": "ಯಾವುದೇ ಪ್ರಕಟಣೆಗಳು ಅಥವಾ ಎಚ್ಚರಿಕೆಗಳು ಪ್ರಸ್ತುತ ಸಕ್ರಿಯವಾಗಿಲ್ಲ.",
    "Timings:": "ಸಮಯ:",
    "Election": "ಚುನಾವಣೆ",
    "Electricity Cutoff": "ವಿದ್ಯುತ್ ಕಡಿತ",
    "Water Cutoff": "ನೀರು ಕಡಿತ",
    "Water Supplying": "ನೀರು ಸರಬರಾಜು",
    "Road Construction": "ರಸ್ತೆ ನಿರ್ಮಾಣ",
    "Road Blockage": "ರಸ್ತೆ ತಡೆ",

    // Miscellaneous relationship translates
    "self": "ಸ್ವತಃ",
    "spouse": "ಜೀವನಸಂಗಾತಿ",
    "son": "ಮಗ",
    "daughter": "ಮಗಳು",
    "father": "ತಂದೆ",
    "mother": "ತಾಯಿ",
    "other": "ಇತರ",

    // Submissions, Statuses and Categories
    "Pending": "ಬಾಕಿ ಇದೆ",
    "In Progress": "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
    "Resolved": "ಪರಿಹರಿಸಲಾಗಿದೆ",
    "Rejected": "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
    "Approved": "ಅನುಮೋದಿಸಲಾಗಿದೆ",
    "All": "ಎಲ್ಲಾ",
    "Pending Action": "ಬಾಕಿ ಇರುವ ಕ್ರಮ",

    "water_leakage": "ನೀರು ಸೋರಿಕೆ",
    "road_damage": "ರಸ್ತೆ ಹಾನಿ",
    "garbage_dump": "ಕಸದ ರಾಶಿ",
    "electricity_issue": "ವಿದ್ಯುತ್ ಸಮಸ್ಯೆ",
    "drainage_issue": "ಚರಂಡಿ ಸಮಸ್ಯೆ",

    "WATER LEAKAGE": "ನೀರು ಸೋರಿಕೆ",
    "ROAD DAMAGE": "ರಸ್ತೆ ಹಾನಿ",
    "GARBAGE DUMP": "ಕಸದ ರಾಶಿ",
    "ELECTRICITY ISSUE": "ವಿದ್ಯುತ್ ಸಮಸ್ಯೆ",
    "DRAINAGE ISSUE": "ಚರಂಡಿ ಸಮಸ್ಯೆ",
    "WATER SUPPLY": "ನೀರು ಸರಬರಾಜು",
    "ROADS": "ರಸ್ತೆಗಳು",
    "GARBAGE": "ಕಸ",
    "ELECT": "ವಿದ್ಯುತ್"
  },
  hi: {
    // Header & Landing
    features: "विशेषताएं",
    howItWorks: "यह कैसे काम करता है",
    community: "समुदाय",
    reportComplaint: "शिकायत दर्ज करें",
    schemes: "योजनाएं",
    profile: "प्रोफ़ाइल",
    dashboard: "डैशबोर्ड",
    login: "लॉगिन",
    logout: "लॉग आउट",
    heroTitleLight: "ग्राम पंचायतों का",
    heroTitleMiddle: " सशक्तिकरण।",
    heroTitleBlue: "गांवों का",
    heroTitleEnd: " पुनरुद्धार।",
    heroDesc: "ग्रामीण समुदायों के लिए टूटी स्ट्रीट लाइट, पानी की आपूर्ति की कमी और स्वच्छता जैसी नागरिक समस्याओं की रिपोर्ट करने के लिए एक समर्पित डिजिटल पोर्टल।",
    btnReport: "गांव की शिकायत दर्ज करें",
    activeStatus: "लाइव",
    precisionTitle: "हमारे गांवों के लिए",
    precisionField: "स्मार्ट शासन।",
    precisionDesc: "हमारा प्लेटफॉर्म सटीक जीपीएस निर्देशांक और फोटो अपलोड का उपयोग करके नागरिक शिकायतों का नक्शा तैयार करता है, और त्वरित समाधान के लिए कार्यों को सीधे पंचायत क्षेत्र कार्यकर्ताओं को भेजता है।",
    evidenceLabel: "सत्यापन योग्य सार्वजनिक कार्य",
    accuracyLabel: "पंचायत प्रतिक्रिया समय",
    monitoringLabel: "पंचायत कार्यप्रवाह",
    smartPortal: "स्मार्ट ग्राम पंचायत पोर्टल",
    unifiedEco: "एकीकृत ग्रामीण",
    ecosystem: "पारिस्थितिकी तंत्र।",
    reportingTitle: "ग्रामीण रिपोर्टिंग",
    reportingDesc: "लाइव फोटो सबूत के साथ पानी के रिसाव, सड़क क्षति, बिजली कटौती या कचरे की समस्याओं की रिपोर्ट करें।",
    adminTitle: "पंचायत प्रबंधन",
    adminDesc: "पंचायत प्रशासक और सरपंच शिकायतों को मंजूरी देते हैं, बजट आवंटित करते हैं और कार्यकर्ताओं को तैनात करते हैं।",
    volunteerTitle: "क्षेत्र समाधान",
    volunteerDesc: "क्षेत्र कार्यकर्ता कार्यों को प्राप्त करते हैं, बुनियादी ढांचे की समस्याओं को हल करते हैं और सत्यापन रिपोर्ट अपलोड करते हैं।",

    // Sidebar & Menus
    home: "होम",
    systemOverview: "सिस्टम अवलोकन",
    fieldWorkers: "क्षेत्र कार्यकर्ता",
    complaintsMgmt: "शिकायतें",
    settings: "सेटिंग्स",
    sysAdmin: "सिस्टम एडमिन",
    citizen: "नागरिक",
    budget: "पंचायत बजट",
    meetings: "बैठकें और कार्यवृत्त",
    taxes: "संपत्ति कर",
    broadcasts: "पंचायत प्रसारण",

    // Admin Dashboard Elements
    "System Overview": "सिस्टम अवलोकन",
    "GramSuvidha infrastructure dashboard and complaint routing.": "ग्रामसुविधा बुनियादी ढांचा डैशबोर्ड और शिकायत रूटिंग।",
    "TOTAL REQUESTS": "कुल अनुरोध",
    "PENDING ACTION": "लंबित कार्रवाई",
    "SUCCESSFUL RESOLUTIONS": "सफल समाधान",
    "ACTIVE VOLUNTEERS": "सक्रिय स्वयंसेवक",
    "CITIZENS": "नागरिक",
    "Panchayat Financial Intelligence": "पंचायत वित्तीय बुद्धिमत्ता",
    "Revenue and expenditure audit tracking for this fiscal year.": "इस वित्तीय वर्ष के लिए राजस्व और व्यय लेखा परीक्षा ट्रैकिंग।",
    "Allocated Budget": "आवंटित बजट",
    "State/Central Allocation": "राज्य/केंद्र आवंटन",
    "Taxes Collected": "एकत्रित कर",
    "Tax Recovery": "कर वसूली",
    "Taxes Outstanding": "बकाया कर",
    "Pending Collection": "लंबित संग्रह",
    "Grievance Expenses": "शिकायत निवारण व्यय",
    "Spent on Resolutions": "समाधान पर खर्च",
    "Available Balance": "उपलब्ध शेष राशि",
    "Panchayat Cash Reserve": "पंचायत नकद आरक्षित निधि",
    "Complaint Priority Distribution": "शिकायत प्राथमिकता वितरण",
    "Real-time breakdown of filed complaints categorized by priority.": "प्राथमिकता के आधार पर वर्गीकृत शिकायतों का वास्तविक समय विश्लेषण।",
    "High Priority Tasks": "उच्च प्राथमिकता वाले कार्य",
    "Medium Priority Tasks": "मध्यम प्राथमिकता वाले कार्य",
    "Low Priority Tasks": "निम्न प्राथमिकता वाले कार्य",
    "Live Status": "लाइव स्थिति",
    "Operational lifecycle phase.": "परिचालन जीवनचक्र चरण।",
    "Incidents": "घटनाएँ",
    "System Intel": "सिस्टम इंटेल",
    "Real-time intelligence computed from your MongoDB data.": "आपके मोंगोडीबी डेटा से वास्तविक समय में आकलित जानकारी।",
    "LIVE": "लाइव",
    "Last updated": "अंतिम अपडेट",
    "Peak Submission Hours": "उच्चतम सबमिशन घंटे",
    "Volunteer Force Status": "स्वयंसेवक बल की स्थिति",
    "Complaint Resolution Rate": "शिकायत समाधान दर",
    "High Priority Backlog": "उच्च प्राथमिकता बैकलॉग",
    "Unassigned Complaints": "अनावंटित शिकायतें",
    "Top Complaint Category": "शीर्ष शिकायत श्रेणी",
    "DETECTED": "पता लगाया गया",
    "HIGH": "उच्च",
    "NEEDS ATTENTION": "ध्यान देने की आवश्यकता है",
    "URGENT": "अति आवश्यक",
    "CLEAR": "साफ़",
    "ANALYSIS": "विश्लेषण",
    "MONITORING": "निगरानी",
    "LOW": "कम",
    "MODERATE": "मध्यम",
    "EXCELLENT": "उत्कृष्ट",
    "ACTION NEEDED": "कार्रवाई की आवश्यकता है",
    "Connection issue — showing last known data": "कनेक्शन समस्या — अंतिम ज्ञात डेटा दिखा रहा है",
    "Could not load system intel": "सिस्टम जानकारी लोड नहीं हो सकी",
    "Make sure the backend server is running": "सुनिश्चित करें कि बैकएंड सर्वर चल रहा है",
    "Retry": "पुनः प्रयास करें",
    "VIEW OPERATIONAL LOG": "परिचालन लॉग देखें",
    "System Operational Logs": "सिस्टम परिचालन लॉग",
    "Real-time status updates and admin action tracking.": "वास्तविक समय स्थिति अपडेट और व्यवस्थापक कार्रवाई ट्रैकिंग।",
    "Close Logs": "लॉग बंद करें",
    "Administrative Shortcuts": "प्रशासनिक शॉर्टकट",
    "Quick links to perform administrative operations across the Panchayat modules.": "पंचायत मॉड्यूल में प्रशासनिक संचालन करने के लिए त्वरित लिंक।",
    "Log Council Meeting": "परिषद की बैठक दर्ज करें",
    "Log dates, topics discussed, citizen queries, solutions, and email minutes.": "तिथियां, चर्चा के विषय, नागरिकों के प्रश्न, समाधान और ईमेल कार्यवृत्त दर्ज करें।",
    "Open Logger": "लॉगर खोलें",
    "Configure Annual Budget": "वार्षिक बजट कॉन्फ़िगर करें",
    "Set total budget, allocate itemized sector funds, and trigger citizen email notifications.": "कुल बजट निर्धारित करें, मदवार फंड आवंटित करें, और नागरिक ईमेल सूचनाएं भेजें।",
    "Allocate Budget": "बजट आवंटित करें",
    "Manage Complaints": "शिकायतें प्रबंधित करें",
    "Dispatch field workers, audit resolution status, and manage resolution ledgers.": "क्षेत्र कार्यकर्ताओं को भेजें, समाधान स्थिति का ऑडिट करें और समाधान बहीखाता प्रबंधित करें।",
    "Review Queue": "कतार की समीक्षा करें",
    "Property Tax Assessments": "संपत्ति कर आकलन",
    "Calculate local property taxes, register assessments, and audit ledger balances.": "स्थानीय संपत्ति करों की गणना करें, आकलन दर्ज करें और बहीखाता शेष का ऑडिट करें।",
    "Assign Assessment": "आकलन असाइन करें",
    "Active Grievances Queue": "सक्रिय शिकायत कतार",
    "Latest unresolved citizen complaints requiring worker assignment.": "कार्यकर्ता आवंटन की आवश्यकता वाली नवीनतम अनसुलझी शिकायतें।",
    "Open Full Ledger": "बहीखाता खोलें",
    "Hello": "नमस्ते",
    "Use this board to track pending grievances, assign public works, configure annual budgets, and publish minutes.": "लंबित शिकायतों को ट्रैक करने, सार्वजनिक कार्यों को आवंटित करने, वार्षिक बजट कॉन्फ़िगर करने और बैठकों को प्रकाशित करने के लिए इस बोर्ड का उपयोग करें।",
    "Gram Panchayat Administrator Dashboard": "ग्राम पंचायत प्रशासक डैशबोर्ड",
    "PENDING": "लंबित",
    "IN PROGRESS": "प्रगति पर है",
    "RESOLVED": "हल किया गया",
    "Awaiting Review": "समीक्षा की प्रतीक्षा में",

    // Citizen Dashboard Elements
    "Citizen Dashboard": "नागरिक डैशबोर्ड",
    "Welcome back": "स्वागत है",
    "Track and manage your reported issues.": "अपनी दर्ज की गई शिकायतों और आवेदनों को ट्रैक और प्रबंधित करें।",
    "New Complaint": "नई शिकायत",
    "Total": "कुल",
    "Under Review": "समीक्षा के अधीन",
    "Resolved": "हल किया गया",
    "Track Complaint or Scheme": "शिकायत या योजना ट्रैक करें",
    "Enter your unique tracking ID (COMP-XXXXXXXX or SCH-XXXXXXXX) to check its status and download the receipt.": "अपनी शिकायत या आवेदन की स्थिति की जांच करने के लिए विशिष्ट ट्रैकिंग आईडी दर्ज करें।",
    "Track Status": "स्थिति ट्रैक करें",
    "View Receipt": "रसीद देखें",
    "Participatory Budgeting": "भागीदारी बजटिंग",
    "Every tax rupee paid by citizens is funneled back directly into village development budgets. Click below to inspect our annual Panchayat allocation values.": "नागरिकों द्वारा भुगतान किया गया प्रत्येक कर सीधे ग्राम विकास बजट में उपयोग किया जाता है। पंचायत आवंटन देखने के लिए नीचे क्लिक करें।",
    "View Panchayat Budget": "पंचायत बजट देखें",
    "My Submissions": "मेरी प्रस्तुतियाँ",
    "Track the live progress of your reported issues.": "अपनी दर्ज की गई समस्याओं की लाइव प्रगति को ट्रैक करें।",
    "All": "सभी",
    "Incident": "घटना",
    "Current Status": "वर्तमान स्थिति",
    "Incident Location": "घटना का स्थान",
    "Progress Stage": "प्रगति चरण",
    "Registered": "पंजीकृत",
    "Verified Entry": "सत्यापित प्रविष्टि",
    "Government Schemes Tailored to Your Reports": "आपकी शिकायतों के अनुसार कल्याणकारी योजनाएं",
    "Based on your village reports, you might be eligible for these development & welfare programs.": "आपके गांव की रिपोर्ट के आधार पर, आप इन विकास और कल्याण कार्यक्रमों के पात्र हो सकते हैं।",
    "RECOMMENDED": "अनुशंसित",
    "View Expanded Details": "विस्तृत विवरण देखें",
    "Complaint Analytics": "शिकायत विश्लेषण",
    "Visual overview of your reporting activity.": "आपकी शिकायत गतिविधियों का विश्लेषणात्मक अवलोकन।",
    "Issues By Category": "श्रेणी के अनुसार शिकायतें",
    "Resolution Status": "समाधान की स्थिति",

    // New Broadcast & Language selection elements
    selectLangTitle: "अपनी पसंदीदा भाषा चुनें",
    selectLangDesc: "वह भाषा चुनें जिसमें आप संवाद करना और पोर्टल चलाना चाहते हैं।",
    langSaveBtn: "सहेजें और जारी रखें",
    broadcastTitle: "पंचायत प्रसारण अलर्ट",
    broadcastFormTitle: "नया प्रसारण संदेश बनाएं",
    broadcastListTitle: "सक्रिय प्रसारण बोर्ड",
    btnBroadcast: "प्रसारण जारी करें",
    categoryLabel: "अलर्ट श्रेणी",
    dateLabel: "निर्धारित तिथि",
    timingsLabel: "समय / विवरण",
    descLabel: "विस्तृत प्रसारण विवरण",
    successBroadcast: "प्रसारण अलर्ट सफलतापूर्वक सभी नागरिकों को ईमेल और डैशबोर्ड अधिसूचना के माध्यम से भेजा गया!",

    // Profile Elements
    "Citizen Profile": "नागरिक प्रोफ़ाइल",
    "Admin Profile": "प्रशासक प्रोफ़ाइल",
    "View or edit your residency details, contact numbers, and check your assigned Panchayat Administrator.": "अपने निवास का विवरण, संपर्क नंबर देखें या संपादित करें और अपने आवंटित पंचायत प्रशासक की जांच करें.",
    "View or edit your administrative details and check system info.": "अपने प्रशासनिक विवरण देखें या संपादित करें और सिस्टम जानकारी की जांच करें.",
    "Cancel Edit": "संपादन रद्द करें",
    "Edit Profile": "प्रोफ़ाइल संपादित करें",
    "Profile Credentials": "प्रोफ़ाइल क्रेडेंशियल",
    "Email Address": "ईमेल पता",
    "Contact Number": "संपर्क नंबर",
    "Age (Years)": "आयु (वर्ष)",
    "Gender": "लिंग",
    "Registered Village": "पंजीकृत गाँव",
    "Application Language": "एप्लिकेशन भाषा",
    "My Assigned Panchayat Administrator": "मेरे आवंटित पंचायत प्रशासक",
    "Admin Name": "प्रशासक का नाम",
    "Admin Phone": "प्रशासक का फोन",
    "Update Particulars": "विवरण अपडेट करें",
    "Full Name": "पूरा नाम",
    "Phone Number": "फ़ोन नंबर",
    "Age": "आयु",
    "Select gender": "लिंग चुनें",
    "Registered Village (Locked)": "पंजीकृत गाँव (लॉक किया हुआ)",
    "Citizens cannot change their village name. Please contact your Panchayat office for address verification changes.": "नागरिक अपने गाँव का नाम नहीं बदल सकते। पता सत्यापन परिवर्तन के लिए कृपया अपने पंचायत कार्यालय से संपर्क करें।",
    "Cancel": "रद्द करें",
    "Save Changes": "बदलाव सहेजें",
    "My Scheme Applications": "मेरे योजना आवेदन",
    "You haven't applied for any schemes yet.": "आपने अभी तक किसी भी योजना के लिए आवेदन नहीं किया है।",
    "Pucca": "पक्का",
    "Semi-Pucca": "सेमी-पक्का",
    "Kutcha": "कच्चा",
    "None": "कोई नहीं",
    "Male": "पुरुष",
    "Female": "महिला",
    "Other": "अन्य",
    "Report Civic Grievance": "नागरिक शिकायत दर्ज करें",
    "Report water supply leaks, broken streetlights, or road potholes with photo uploads and automatic GPS lock.": "फोटो अपलोड और स्वचालित जीपीएस लॉक के साथ पानी की आपूर्ति के रिसाव, टूटी स्ट्रीट लाइट या सड़क के गड्ढों की रिपोर्ट करें।",
    "Government Scheme's": "सरकारी योजनाएं",
    "Explore, check eligibility, and apply for national welfare programs (PMAY, MGNREGA) with digital receipts.": "डिजिटल रसीदों के साथ राष्ट्रीय कल्याण कार्यक्रमों (PMAY, MGNREGA) का पता लगाएं, पात्रता जांचें और आवेदन करें।",
    "Panchayat Budget": "पंचायत बजट",
    "Inspect annual development budgets, funds reserves, and itemized sector allocations visually.": "वार्षिक विकास बजट, निधि आरक्षित और मदवार क्षेत्र आवंटन की जांच करें।",
    "Property Taxes": "संपत्ति कर",
    "Calculate annual property taxes using official government rules, pay dues online, and download receipts.": "आधिकारिक सरकारी नियमों का उपयोग करके वार्षिक संपत्ति कर की गणना करें, ऑनलाइन भुगतान करें और रसीदें डाउनलोड करें।",
    "Citizen Portal Dashboard": "नागरिक पोर्टल डैशबोर्ड",
    "Welcome to GramSuvidha Digital Panchayat": "ग्रामसुविधा डिजिटल पंचायत में आपका स्वागत है",
    "Hello, ": "नमस्ते, ",
    ". Access Panchayat services, track status of grievances, apply for welfare benefits, and check public council decisions online.": ". पंचायत सेवाओं तक पहुँचें, शिकायतों की स्थिति को ट्रैक करें, कल्याणकारी लाभों के लिए आवेदन करें, और सार्वजनिक परिषद के निर्णयों की ऑनलाइन जाँच करें।",
    "Panchayat Digital Notice Board": "पंचायत डिजिटल सूचना पट्ट",
    "IMPORTANT ANNOUNCEMENT": "महत्वपूर्ण घोषणा",
    "June 2026": "जून 2026",
    "Property Tax Assessment Deadline": "संपत्ति कर निर्धारण समय सीमा",
    "Citizens are requested to compute and settle their property tax bills for the current assessment cycle. Late filings will attract standard municipal cesses. Pay directly under the \"Property Taxes\" path in the sidebar.": "नागरिकों से अनुरोध है कि वे वर्तमान मूल्यांकन चक्र के लिए अपने संपत्ति कर बिलों की गणना करें और उनका भुगतान करें। देर से भुगतान करने पर मानक जुर्माना लगाया जाएगा। साइडबार में 'संपत्ति कर' के अंतर्गत सीधे भुगतान करें।",
    "HEALTH DRIVE": "स्वास्थ्य अभियान",
    "Universal Vaccination Camp": "सार्वभौमिक टीकाकरण शिविर",
    "A free village health audit and child immunization camp will be organized at the local Panchayat community building next Monday at 09:00 AM.": "अगले सोमवार सुबह 09:00 बजे स्थानीय पंचायत सामुदायिक भवन में एक निःशुल्क ग्रामीण स्वास्थ्य शिविर और बाल टीकाकरण शिविर आयोजित किया जाएगा।",
    "Recent Council Assembly Minutes": "हालिया परिषद बैठक का कार्यवृत्त",
    "View All Minutes": "सभी कार्यवृत्त देखें",
    "Checking minutes log...": "कार्यवृत्त की जाँच की जा रही है...",
    "No council meeting minutes recorded yet.": "अभी तक कोई परिषद बैठक का कार्यवृत्त दर्ज नहीं किया गया है।",
    "Held:": "आयोजित दिनांक:",
    "Time:": "समय:",
    "Primary Topics Discussed:": "चर्चा किए गए प्राथमिक विषय:",
    "Target Civil Infrastructures before next cycle:": "अगले चक्र से पहले लक्षित नागरिक बुनियादी ढाँचे:",
    "Quick Citizen Actions": "त्वरित नागरिक क्रियाएं",
    "Instant shortcuts to direct services.": "सीधी सेवाओं के लिए त्वरित शॉर्टकट।",
    "Need Assistance?": "क्या आपको सहायता की आवश्यकता है?",
    "If you have questions regarding land records, scheme requirements, or tax values, try querying our AI chatbot helper in the bottom-right corner. It supports Hindi translations too!": "यदि आपके पास भूमि रिकॉर्ड, योजना आवश्यकताओं या कर मूल्यों के बारे में प्रश्न हैं, तो नीचे-दाएं कोने में हमारे एआई चैटबॉट से पूछने का प्रयास करें। यह हिंदी और कन्नड़ अनुवादों का भी समर्थन करता है!",
    "Administrative Command Portal": "प्रशासनिक कमांड पोर्टल",
    "Gram Panchayat Administrator Dashboard": "ग्राम पंचायत प्रशासक डैशबोर्ड",
    ". Use this board to track pending grievances, assign public works, configure annual budgets, and publish minutes.": ". लंबित शिकायतों को ट्रैक करने, सार्वजनिक कार्यों को आवंटित करने, वार्षिक बजट कॉन्फ़िगर करने और बैठकों को प्रकाशित करने के लिए इस बोर्ड का उपयोग करें।",
    "Pending Grievances": "लंबित शिकायतें",
    "Active Field Force": "सक्रिय क्षेत्र बल",
    "Workers": "कार्यकर्ता",
    "Registered Citizens": "पंजीकृत नागरिक",
    "ID:": "आईडी:",
    "N/A": "अनुपलब्ध",
    "Meetings Concluded": "बैठकें संपन्न",
    "sessions": "सत्र",
    "Unpaid Taxes Ledger": "अवैतनिक कर बहीखाता",
    "Properties": "संपत्तियां",
    "Administrative Shortcuts": "प्रशासनिक शॉर्टकट",
    "Quick links to perform administrative operations across the Panchayat modules.": "पंचायत मॉड्यूल में प्रशासनिक संचालन करने के लिए त्वरित लिंक।",
    "Active Grievances Queue": "सक्रिय शिकायत कतार",
    "Latest unresolved citizen complaints requiring worker assignment.": "कार्यकर्ता आवंटन की आवश्यकता वाली नवीनतम अनसुलझी शिकायतें।",
    "Checking queue...": "कतार की जाँच की जा रही है...",
    "No unresolved complaints. Good job!": "कोई अनसुलझी शिकायत नहीं है। बहुत बढ़िया!",
    "Open Full Ledger": "बहीखाता खोलें",
    "Crore": "करोड़",
    "Lakh": "लाख",
    "Panchayat Budget Allocations": "पंचायत बजट आवंटन",
    "Access transparent breakdowns of the Gram Panchayat annual development budgets and visual sector allocations.": "ग्राम पंचायत के वार्षिक विकास बजट और दृश्य क्षेत्र आवंटन के पारदर्शी विवरण तक पहुँचें।",
    "Fiscal Year:": "वित्तीय वर्ष:",
    "FY": "वित्तीय वर्ष",
    "Retrieving Budget Records...": "बजट रिकॉर्ड प्राप्त किए जा रहे हैं...",
    "No budget details registered for fiscal year": "वित्तीय वर्ष के लिए कोई बजट विवरण पंजीकृत नहीं है",
    "Please check back later or select a different year.": "कृपया बाद में जाँच करें या कोई अन्य वर्ष चुनें।",
    "Total Allocated Funds": "कुल आवंटित निधि",
    "Development Objectives": "विकास के उद्देश्य",
    "Sector Percentage Share": "क्षेत्र प्रतिशत हिस्सेदारी",
    "Allocation": "आवंटन",
    "Funds Weight Analysis": "निधि भार विश्लेषण",
    "Itemized Category Allocations": "मदवार श्रेणी आवंटन",
    "Sector Category": "क्षेत्र श्रेणी",
    "Funding Target": "वित्तपोषण लक्ष्य",
    "Amount Allocated": "आवंटित राशि",
    "General Panchayat development works.": "सामान्य पंचायत विकास कार्य।",
    "Gram Sabha Meetings & Minutes": "ग्राम सभा बैठकें और कार्यवृत्त",
    "Keep track of general body discussions, citizen questions, board resolutions, and ongoing infrastructure timelines.": "आम सभा की चर्चाओं, नागरिकों के प्रश्नों, बोर्ड के प्रस्तावों और चल रही बुनियादी ढांचा समय-सीमाओं पर नज़र रखें।",
    "Retrieving meeting logs...": "बैठक के लॉग प्राप्त किए जा रहे हैं...",
    "No meeting minutes registered by the Panchayat administration yet.": "पंचायत प्रशासन द्वारा अभी तक कोई बैठक का कार्यवृत्त दर्ज नहीं किया गया है।",
    "Grievances and discussions are logged after each council assembly.": "प्रत्येक परिषद बैठक के बाद शिकायतें और चर्चाएं दर्ज की जाती हैं।",
    "1. Topics & Details Discussed": "1. चर्चा किए गए विषय और विवरण",
    "2. Grievances Raised by Citizens": "2. नागरिकों द्वारा उठाई गई शिकायतें",
    "3. Solutions & Board Resolutions": "3. समाधान और बोर्ड के प्रस्ताव",
    "4. Immediate Actions Needed": "4. तत्काल आवश्यक कार्रवाई",
    "5. Target Developments Before Next Council Assembly": "5. अगली परिषद बैठक से पहले लक्षित विकास",

    // AdminMeetings
    "Failed to fetch meeting records.": "बैठक के रिकॉर्ड प्राप्त करने में विफल।",
    "Network error loading meetings.": "बैठकें लोड करने में नेटवर्क त्रुटि।",
    "Please fill in all meeting log fields.": "कृपया सभी बैठक लॉग फ़ील्ड भरें।",
    "Meeting minutes registered successfully! Citizens are being notified via email.": "बैठक का विवरण सफलतापूर्वक पंजीकृत! नागरिकों को ईमेल द्वारा सूचित किया जा रहा है।",
    "Failed to register meeting: ": "बैठक पंजीकृत करने में विफल: ",
    "Error registering meeting.": "बैठक पंजीकृत करने में त्रुटि।",
    "Meetings & Minutes Console": "बैठक और कार्यवृत्त कंसोल",
    "Log Gram Panchayat general body minutes, citizen grievances, resolutions, and next target timelines.": "ग्राम पंचायत की सामान्य सभा के कार्यवृत्त, नागरिकों की शिकायतें, प्रस्ताव और अगले लक्ष्य की समयसीमा दर्ज करें।",
    "Log New Meeting Minutes": "नई बैठक के कार्यवृत्त दर्ज करें",
    "Submitted minutes are officially logged and automatically broadcasted to all citizens.": "प्रस्तुत कार्यवृत्त आधिकारिक तौर पर दर्ज किए जाते हैं और स्वचालित रूप से सभी नागरिकों को प्रसारित किए जाते हैं।",
    "Meeting Date": "बैठक की तिथि",
    "Meeting Time": "बैठक का समय",
    "1. Topics & Details Discussed": "1. चर्चा किए गए विषय और विवरण",
    "2. Questions & Grievances Raised by Citizens": "2. नागरिकों द्वारा उठाए गए प्रश्न और शिकायतें",
    "3. Solutions & Resolutions Provided": "3. प्रदान किए गए समाधान और प्रस्ताव",
    "4. Immediate Actions Needed": "4. आवश्यक तत्काल कार्रवाई",
    "5. Infrastructure Targets Before Next Meeting": "5. अगली बैठक से पहले बुनियादी ढांचा लक्ष्य",
    "Record summary details of key topics addressed in the general body...": "सामान्य सभा में संबोधित प्रमुख विषयों के सारांश विवरण दर्ज करें...",
    "Log specific queries, complaints, or feedback brought up by the resident body...": "निवासी निकाय द्वारा उठाए गए विशिष्ट प्रश्नों, शिकायतों या प्रतिक्रिया को दर्ज करें...",
    "Summarize the answers, options, or formal resolutions agreed by the board...": "बोर्ड द्वारा सहमत उत्तरों, विकल्पों या औपचारिक प्रस्तावों का सारांश दें...",
    "Outline immediate tasks, assigned officers, or fast-track steps...": "तत्काल कार्यों, आवंटित अधिकारियों या त्वरित कदमों की रूपरेखा तैयार करें...",
    "Specific civil/development goals (e.g. Completing school paving, setting up solar cells)...": "विशिष्ट नागरिक/विकास लक्ष्य (जैसे स्कूल फ़र्श पूरा करना, सौर सेल स्थापित करना)...",
    "Publishing & Broadcasting Minutes...": "कार्यवृत्त प्रकाशित और प्रसारित किया जा रहा है...",
    "Save & Publish Meeting Minutes": "बैठक के कार्यवृत्त सहेजें और प्रकाशित करें",
    "Meeting History List": "बैठक इतिहास सूची",
    "Historical record of Panchayat minutes logged.": "दर्ज किए गए पंचायत कार्यवृत्त का ऐतिहासिक रिकॉर्ड।",
    "Loading records...": "रिकॉर्ड लोड हो रहे हैं...",
    "No meetings recorded yet.": "अभी तक कोई बैठक दर्ज नहीं की गई है।",
    "Discussion:": "चर्चा:",
    "Emailed to Citizens": "नागरिकों को ईमेल किया गया",
    "Local copy only": "केवल स्थानीय प्रति",

    // AdminTaxes
    "Please fill out Owner Name and Citizen Email": "कृपया मालिक का नाम और नागरिक ईमेल भरें",
    "Property Tax assessment registered successfully!": "संपत्ति कर मूल्यांकन सफलतापूर्वक पंजीकृत!",
    "Failed to create assessment": "मूल्यांकन बनाने में विफल",
    "Network error creating assessment": "मूल्यांकन बनाने में नेटवर्क त्रुटि",
    "Property Taxes Management": "संपत्ति कर प्रबंधन",
    "Audit property details, compute Indian government rules-based taxes, and log local ledger assessments.": "संपत्ति विवरण का ऑडिट करें, भारत सरकार के नियमों के आधार पर करों की गणना करें, और स्थानीय बहीखाता मूल्यांकन दर्ज करें।",
    "Property Tax Ledger": "संपत्ति कर बहीखाता",
    "Search by ID or owner...": "आईडी या मालिक द्वारा खोजें...",
    "All Statuses": "सभी स्थितियां",
    "Paid": "भुगतान किया गया",
    "Unpaid": "अवैतनिक",
    "Owner / Property ID": "मालिक / संपत्ति आईडी",
    "Details": "विवरण",
    "Annual Tax": "वार्षिक कर",
    "Status": "स्थिति",
    "Receipt / Txn ID": "रसीद / लेनदेन आईडी",
    "No records found.": "कोई रिकॉर्ड नहीं मिला।",
    "Residential": "आवासीय",
    "Commercial": "व्यावसायिक",
    "Industrial": "औद्योगिक",
    "Vacant": "खाली",
    "Pucca": "पक्का",
    "Semi-Pucca": "अर्ध-पक्का",
    "Kutcha": "कच्चा",
    "construction": "निर्माण",
    "Loading ledger...": "बहीखाता लोड हो रहा है...",
    "Assign Tax Assessment": "कर निर्धारण सौंपें",
    "Create property tax bills manually for village citizens.": "ग्रामीण नागरिकों के लिए संपत्ति कर बिल मैन्युअल रूप से बनाएं।",
    "Citizen Email Address": "नागरिक का ईमेल पता",
    "Owner Full Name": "मालिक का पूरा नाम",
    "Type": "प्रकार",
    "Construction": "निर्माण",
    "Area (sq ft)": "क्षेत्रफल (वर्ग फुट)",
    "Assessed Tax:": "निर्धारित कर:",
    "Registering...": "पंजीकरण किया जा रहा है...",
    "Register Property & Bill": "संपत्ति और बिल पंजीकृत करें",

    // ComplaintsManagement
    "Failed to update complaint": "शिकायत अपडेट करने में विफल",
    "Network error": "नेटवर्क त्रुटि",
    "Failed to update status": "स्थिति अपडेट करने में विफल",
    "Complaints": "शिकायतें",
    "Workers Active": "कार्यकर्ता सक्रिय",
    "Detailed review and resolution of civic reports.": "नागरिक रिपोर्टों की विस्तृत समीक्षा और समाधान।",
    "Civic Complaints": "नागरिक शिकायतें",
    "Search by ID or details...": "आईडी या विवरण द्वारा खोजें...",
    "Loading complaints...": "शिकायतें लोड हो रही हैं...",
    "Complaint Details": "शिकायत का विवरण",
    "Assigned Force": "आवंटित बल",
    "Incident Location": "घटना का स्थान",
    "Actions": "कार्रवाई",
    "No complaints found matching current search and filters.": "वर्तमान खोज और फ़िल्टर से मेल खाने वाली कोई शिकायत नहीं मिला।",
    "View": "देखें",
    "Awaiting Review": "समीक्षा की प्रतीक्षा है",
    "None": "कोई नहीं",
    "Complaint Details — ": "शिकायत विवरण — ",
    "Category": "श्रेणी",
    "Citizen Details": "नागरिक विवरण",
    "Name:": "नाम:",
    "Phone:": "फ़ोन:",
    "Description": "विवरण",
    "Location": "स्थान",
    "Visual Evidence & Attachments": "दृश्य साक्ष्य और संलग्नक",
    "View Full Image": "पूरी छवि देखें",
    "Open": "खोलें",
    "No attachments provided.": "कोई संलग्नक प्रदान नहीं किया गया।",
    "Update Status": "स्थिति अपडेट करें",
    "Assign Worker": "कार्यकर्ता असाइन करें",
    "Resolution Cost (₹)": "समाधान लागत (₹)",
    "Cost Description": "लागत विवरण",
    "Approve": "स्वीकार करें",
    "Reject": "अस्वीकार करें",
    "Close": "बंद करें",
    "Save Changes": "बदलाव सहेजें",

    // FieldWorkers
    "Please fill in all fields": "कृपया सभी क्षेत्रों को भरें",
    "Worker registered successfully!": "कार्यकर्ता सफलतापूर्वक पंजीकृत!",
    "Failed to register worker": "कार्यकर्ता पंजीकृत करने में विफल",
    "Worker marked as": "कार्यकर्ता को इस रूप में चिह्नित किया गया",
    "Failed to toggle status": "स्थिति बदलने में विफल",
    "Network error updating status": "स्थिति अपडेट करने में नेटवर्क त्रुटि",
    "Field Workers": "क्षेत्र कार्यकर्ता",
    "Manage and track the active GramSuvidha workforce.": "सक्रिय ग्रामसुविधा कार्यबल का प्रबंधन और ट्रैकिंग करें।",
    "Refresh List": "सूची ताज़ा करें",
    "Close Registry": "पंजीकरण बंद करें",
    "Click Photo to Add": "जोड़ने के लिए फ़ोटो पर क्लिक करें",
    "Total Workers": "कुल कार्यकर्ता",
    "Assigned Cases": "सौंपे गए मामले",
    "Force Overview": "बल अवलोकन",
    "Available Workers": "उपलब्ध कार्यकर्ता",
    "All Workers": "सभी कार्यकर्ता",
    "Search workers...": "कार्यकर्ताओं की खोज करें...",
    "Loading workers...": "कार्यकर्ताओं को लोड किया जा रहा है...",
    "Photo": "फ़ोटो",
    "Worker Identity": "कार्यकर्ता पहचान",
    "Area / Village": "क्षेत्र / गांव",
    "Contact": "संपर्क",
    "Demographics": "जनसांख्यिकी",
    "Active Status Toggle": "सक्रिय स्थिति टॉगल",
    "No field workers found matching search.": "खोज से मेल खाने वाला कोई क्षेत्र कार्यकर्ता नहीं मिला।",
    "Y/O": "वर्ष",
    "Male": "पुरुष",
    "Female": "महिला",
    "Other": "अन्य",
    "ACTIVE": "सक्रिय",
    "INACTIVE": "निष्क्रिय",
    "Toggle active status": "सक्रिय स्थिति टॉगल करें",
    "Add New Worker": "नया कार्यकर्ता जोड़ें",
    "Register a new field worker for the GramSuvidha force.": "ग्रामसुविधा बल के लिए एक नए क्षेत्र कार्यकर्ता को पंजीकृत करें।",
    "Full Name": "पूरा नाम",
    "Phone Number": "फ़ोन नंबर",
    "Age": "आयु",
    "Gender": "लिंग",
    "Assigned Village / Ward": "आवंटित गांव / वार्ड",
    "Clear": "साफ़ करें",
    "Register Worker": "कार्यकर्ता का पंजीकरण करें",

    // SchemeApplications
    "Failed to fetch applications.": "आवेदन प्राप्त करने में विफल।",
    "Network error. Is the backend running?": "नेटवर्क त्रुटि। क्या बैकएंड चल रहा है?",
    "Failed to update status.": "स्थिति अपडेट करने में विफल।",
    "Error connecting to backend.": "बैकएंड से कनेक्ट करने में त्रुटि।",
    "Admin Scheme's Portal": "प्रशासक योजना पोर्टल",
    "Manage scheme catalog listings and review submitted applications from citizens.": "योजना कैटलॉग लिस्टिंग का प्रबंधन करें और नागरिकों से प्रस्तुत आवेदनों की समीक्षा करें।",
    "Available Schemes Catalog": "उपलब्ध योजनाएं कैटलॉग",
    "Pradhan Mantri Awas Yojana (PMAY)": "प्रधानमंत्री आवास योजना (PMAY)",
    "Housing for the rural poor.": "ग्रामीण गरीबों के लिए आवास।",
    "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)": "महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम (MGNREGA)",
    "Guarantees 100 days of wage employment.": "100 दिनों के सवैतनिक रोजगार की गारंटी।",
    "PM Kisan Samman Nidhi (PM-KISAN)": "पीएम किसान सम्मान निधि (PM-KISAN)",
    "Income support to all landholding farmer families.": "सभी भूमिधारक किसान परिवारों को आय सहायता।",
    "National Social Assistance Programme (NSAP)": "राष्ट्रीय सामाजिक सहायता कार्यक्रम (NSAP)",
    "Pension scheme for elderly citizens.": "वृद्ध नागरिकों के लिए पेंशन योजना।",
    "Sukanya Samriddhi Yojana (SSY)": "सुकन्या समृद्धि योजना (SSY)",
    "Savings scheme targeted at parents of girl children.": "बालिकाओं के माता-पिता के लिए बचत योजना।",
    "Jal Jeevan Mission (Har Ghar Jal)": "जल जीवन मिशन (हर घर जल)",
    "Safe and adequate drinking water through individual household tap connections.": "व्यक्तिगत घरेलू नल कनेक्शन के माध्यम से सुरक्षित और पर्याप्त पेयजल।",
    "Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)": "दीनदयाल उपाध्याय ग्रामीण कौशल योजना (DDU-GKY)",
    "Placement linked skill development program for rural youth.": "ग्रामीण युवाओं के लिए प्लेसमेंट लिंक्ड कौशल विकास कार्यक्रम।",
    "Eligible Age Range:": "पात्र आयु सीमा:",
    "years": "वर्ष",
    "Income Cap Limit:": "आय सीमा:",
    "/ year": "/ वर्ष",
    "View Scheme Setup": "योजना सेटअप देखें",
    "Submitted Applications Registry": "प्रस्तुत आवेदन रजिस्ट्री",
    "Pending Action": "लंबित कार्रवाई",
    "Applicant Name": "आवेदक का नाम",
    "Relationship": "संबंध",
    "Income Declared": "घोषित आय",
    "Submitted On": "को प्रस्तुत किया गया",
    "ID Document:": "पहचान दस्तावेज:",
    "Uploaded File:": "अपलोड की गई फ़ाइल:",
    "View Document": "दस्तावेज़ देखें",
    "Approve App": "आवेदन स्वीकार करें",
    "Reject App": "आवेदन अस्वीकार करें",
    "Set Back to Pending": "वापस लंबित पर सेट करें",
    "Overview:": "अवलोकन:",
    "Benefits:": "लाभ:",
    "Eligibility Criteria:": "पात्रता मानदंड:",
    "Documents Required:": "आवश्यक दस्तावेज:",
    "Close Guidelines": "दिशा-निर्देश बंद करें",
    "Loading scheme applications...": "योजना आवेदनों को लोड किया जा रहा है...",
    "No scheme applications have been submitted yet.": "अभी तक कोई योजना आवेदन जमा नहीं किया गया है।",

    // CitizenBroadcasts
    "Stay updated with important announcements regarding local elections, water supply schedules, power cutoffs, and road constructions in our village.": "हमारे गांव में स्थानीय चुनावों, जलापूर्ति कार्यक्रम, बिजली कटौती और सड़क निर्माण के संबंध में महत्वपूर्ण घोषणाओं से अपडेट रहें।",
    "No announcements or alerts are currently active.": "वर्तमान में कोई घोषणा या अलर्ट सक्रिय नहीं है।",
    "Timings:": "समय:",
    "Election": "चुनाव",
    "Electricity Cutoff": "बिजली कटौती",
    "Water Cutoff": "पानी की कटौती",
    "Water Supplying": "जलापूर्ति",
    "Road Construction": "सड़क निर्माण",
    "Road Blockage": "सड़क मार्ग बंद",

    // Miscellaneous relationship translates
    "self": "स्वयं",
    "spouse": "जीवनसाथी",
    "son": "बेटा",
    "daughter": "बेटी",
    "father": "पिता",
    "mother": "माता",
    "other": "अन्य",

    // Submissions, Statuses and Categories
    "Pending": "लंबित",
    "In Progress": "प्रगति पर है",
    "Resolved": "हल किया गया",
    "Rejected": "अस्वीकृत",
    "Approved": "अनुमोदित",
    "All": "सभी",
    "Pending Action": "लंबित कार्रवाई",

    "water_leakage": "पानी का रिसाव",
    "road_damage": "सड़क की क्षति",
    "garbage_dump": "कचरे का ढेर",
    "electricity_issue": "बिजली की समस्या",
    "drainage_issue": "जल निकासी की समस्या",

    "WATER LEAKAGE": "पानी का रिसाव",
    "ROAD DAMAGE": "सड़क की क्षति",
    "GARBAGE DUMP": "कचरे का ढेर",
    "ELECTRICITY ISSUE": "बिजली की समस्या",
    "DRAINAGE ISSUE": "जल निकासी की समस्या",
    "WATER SUPPLY": "जलापूर्ति",
    "ROADS": "सड़कें",
    "GARBAGE": "कचरा",
    "ELECT": "बिजली"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const setLanguage = (lang) => {
    if (translations[lang] || lang === 'en') {
      setLanguageState(lang);
      localStorage.setItem('language', lang);
      
      const user = JSON.parse(localStorage.getItem('user') || '{}');
      if (user && user._id) {
        user.language = lang;
        localStorage.setItem('user', JSON.stringify(user));
      }
    }
  };

  const t = (key) => {
    if (!key) return '';
    if (language === 'en') return key;
    const langDict = translations[language] || {};
    const upperKey = typeof key === 'string' ? key.toUpperCase() : '';
    const lowerKey = typeof key === 'string' ? key.toLowerCase() : '';
    return langDict[key] || (upperKey && langDict[upperKey]) || (lowerKey && langDict[lowerKey]) || translations.en[key] || key;
  };

  const toggleLanguage = () => {
    if (language === 'en') setLanguage('kn');
    else if (language === 'kn') setLanguage('hi');
    else setLanguage('en');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
